{// Parastā liturģiskā laika 1. un 3.ned. himnas
var hinmaVesperes_1_6 = '<p class="psalms1">Dievs, visu lietu Radītāj<br>un debess juma pārvaldniek,<br>Tu dienu ietērp spožumā<br>un nakti – miega klusumā.</p><p class="psalms2">Lai mūsu miesas gurdenās<br>nakts mierā atkal spēku rod,<br>lai prāta nemiers noplok mums,<br>no sirds lai skumjas aiziet prom.</p><p class="psalms1">Paldies Tev, Kungs, par dienu šo,<br>ar lūgsnām nakti sagaidām,<br>nāc grēciniekiem palīgā,<br>šo himnu dziedot, lūdzam mēs.</p><p class="psalms2">Sirds dziļumi Tev dziesmu dzied,<br>balss skanīgā tiem piebalso,<br>pēc Tevis šķīsta dvēs’le alkst,<br>prāts skaidrais pielūdz Tevi vien.</p><p class="psalms1">Kad diena šī būs beigusies,<br>nakts sega pārklās pasauli,<br>lai aizdzen tumsu ticība<br>un naktī ceļu rāda mums.</p><p class="psalms2">Nu Tēvu, Dēlu lūdzam mēs<br>un Garu, kas no Viņiem nāk:<br>Viens Trīsvienībā, Varenais,<br>tos stiprini, kas Tevi lūdz. Āmen.</p>';

var hinmaLaudes_1_0 = '<p class="psalms1">Ak, Radītāj, Dievs mūžīgais,<br>pār nakti, dienu valdi Tu,<br>un laikam dāvā ritumu,<br>lai garlaicīgi nebūtu.</p><p class="psalms2">Jau gailis rītu pavēsta –<br>tas naktī bija nomodā;<br>un ceļiniekam gaisma aust,<br>kas viņu tālāk doties sauc.</p><p class="psalms1">Lūk, rīta zvaigzne iedegas<br>un debess jumu apgaismo,<br>un tie, kas noklīduši bij’,<br>no maldu ceļiem novēršas.</p><p class="psalms2">Ir jūrnieks spēkus atguvis,<br>un trakās bangas rimušās;<br>ar gaiļa dziesmu Pēteris<br>steidz savus grēkus nožēlot.</p><p class="psalms1">Kungs, mazdūšīgos uzlūko,<br>ja mēs tie esam, dziedini,<br>jo skatiens Tavs liek grēkam bēgt<br>un uzmodina nožēlu.</p><p class="psalms2">Nāc mūsu prātus apgaismo<br>un mūsu sirdis modini, –<br>lai Tevi pirmo sveicinām<br>no rīta mēs ar lūgšanām!</p><p class="psalms1">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_1_0 = '<p class="psalms1">Vislabais gaismas Radītāj,<br>kas dienas gaismu dāvā mums,<br>ar jaunās gaismas sākumu<br>Tu radīšanu iesāki.</p><p class="psalms2">Tu rītu līdz ar vakaru<br>par dienu saukt mums noteici.<br>Kad grēka tumsība mums draud,<br>jel klausies, sirds ko lūdz un raud.</p><p class="psalms1">Mūs ļaunus, smagus dara grēks,<br>bet augšup lai mūs ceļ Tavs spēks<br>un, domājot par Tevi, Dievs,<br>mēs grēkiem nepiesaistāmies.</p><p class="psalms2">Pie Tavām durvīm gaidām mēs,<br>līdz debesis mums atvērsies:<br>ļauj, sirds lai bēdas panest var,<br>nāc, mūs no ļauna šķīstus dar’.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_1 = '<p class="psalms1">Tu atspulgs Tēva godībai,<br>kas gaismu nes no Gaismas mums,<br>Tu īstā gaisma, avots tai,<br>un Diena, kas dod dienu mums.</p><p class="psalms2">Tu mūsu Saule patiesā,<br>kas mūžam spīdi brīnišķi,<br>ar Svētā Gara mirdzumu<br>jel mūsu prātus piepildi.</p><p class="psalms1">Mēs balsī Tēvu piesaucam,<br>kas mūžīgs savā godībā<br>un žēlastībā visvarens –<br>Viņš grēka briesmas mazina.</p><p class="psalms2">Lai krietniem darbiem skubina<br>un ienaidnieku savalda,<br>lai grūtībās mūs atbalsta<br>un izturībā stiprina.</p><p class="psalms1">Lai mūsu prātu pārvalda<br>un miesu šķīstu nosargā,<br>lai aizdedz mūsu ticību,<br>ka maldos neiekristu tā.</p><p class="psalms2">Lai Kristus mums ir barība<br>un dzēriens mūsu – ticība,<br>lai noreibstam no Gara mēs –<br>tas dāvā prāta skaidrību.</p><p class="psalms1">Ar prieku šodien dzīvosim:<br>lai tikumība ir kā rīts,<br>kā pusdienlaiks lai ticība,<br>bet dvēsele lai nenoriet.</p><p class="psalms2">Sāk savu ceļu rītausma,<br>mēs gribam redzēt Rītausmu,<br>kur Tēvā Dēls ir pilnībā<br>un Vārdā Tēvs viss izteikts mums. Āmen.</p>';
var hinmaVesperes_1_1 = '<p class="psalms1">Ak, dižais debess veidotāj,<br>Tu ūdeņus no ūdeņiem<br>ar debesjumu atšķīri<br>un devi vietu debesīm.</p><p class="psalms2">Tu liki sauli debesīs<br>un zemi strautiem pildīji,<br>lai ūdens augsni veldzētu<br>un svelme nepostītu to.</p><p class="psalms1">Vissvētais, ielej dvēselēs<br>nu žēlastību mūžīgo,<br>lai vecā grēka paliekas<br>mums jaunos maldos neliek krist.</p><p class="psalms2">Lai ticība mūs apgaismo<br>un prātam dāvā skaidrību,<br>ko pasaulīgās tukšības<br>un viltus nespēj saduļķot.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_2 = '<p class="psalms1">Rau, zemei vēstī rītausma<br>par saules stariem spožajiem,<br>kas krāsās ietērpj pasauli<br>un visam koši mirdzēt liek.</p><p class="psalms2">Ak, Kristu, saule mūžīgā,<br>Tu esi mūsu dzīvība,<br>nu Tevi dziesmām slavējam<br>un ceram skatīt mūžībā.</p><p class="psalms1">Tu esi Tēva gudrība,<br>Vārds, kas mūs visus apgaismo<br>ar brīnišķīgu kārtību,<br>pie sevis velkot dvēseles.</p><p class="psalms2">Dod spēku dienu nodzīvot<br>kā gaismas bērniem dedzīgiem,<br>lai mūsu darbi, tikumi<br>par debess Tēvu liecina.</p><p class="psalms1">Lai visu, kas vien sakāms mums,<br>mēs vienmēr teiktu godīgi,<br>un patiesības dāvātais<br>prieks sirdi ielīksmotu mums.</p><p class="psalms2">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_1_2 = '<p class="psalms1">Ak, dižais Zemes Radītāj,<br>Tu izveidoji sauszemi,<br>no ūdeņiem to nošķirot<br>un dodot stiprus pamatus,</p><p class="psalms2">lai sēkla tajā uzdīgtu<br>un krāšņos ziedos uzplauktu,<br>tad dāsnos augļos nobriestu,<br>kas visas būtnes pamielo.</p><p class="psalms1">Tās brūces, kas ir dvēselē,<br>lai žēlastība sadziedē,<br>lai vainas mazgā nožēla<br>un ļaunas domas izdeldē.</p><p class="psalms2">Lai vairāmies no ļaunā mēs<br>un Tevis teikto izpildām,<br>ar prieku labo saņemam<br>un nāves grēkus nedarām.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_3 = '<p class="psalms1">Jau gaisma uzaust pamalē,<br>nāk Kristus – atkāpieties jūs:<br>nakts tumsa, migla, mākoņi,<br>kas skatu aptumšojat mums.</p><p class="psalms2">Nu saules stari saplosa<br>it visas zemes tumsības,<br>un spožums nāk no debesīm<br>ar krāsām pieliet pasauli.</p><p class="psalms1">Tāpat lai mūsu dvēselei,<br>kas grēka aptumšota skumst,<br>nu mākoņus Dievs aizdzen prom,<br>to vadot dara gaišāku.</p><p class="psalms2">Tu, Kristu, esi vienīgais,<br>kam vērts ir dāvāt dvēseli,<br>ko pielūgt un ko godināt,<br>ko visu mūžu iepazīt.</p><p class="psalms1">Kungs mūsu domas izvērtē<br>un mūsu dzīvi izpēti,<br>jo daudzas lietas vajag tur<br>ar Tavu gaismu attīrīt.</p><p class="psalms2">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_1_3 = '<p class="psalms1">Ak, Dievs vissvētais Debesīs,<br>Tu debesjumu vizošo<br>ar uguns stariem iekrāso,<br>lai gaisma kļūtu krāšņāka.</p><p class="psalms2">Tu liki dienā ceturtā,<br>lai saule spīdēt uzsāktu<br>un mēness viņai sekotu,<br>bet zvaigznes ceļu rādītu.</p><p class="psalms1">Tu tādā veidā noteici,<br>kad dienai, naktij sākums ir,<br>kā mēness fāzes nomainās<br>un citas laika zīmes ar’.</p><p class="psalms2">Jel ļaužu sirdis apgaismo,<br>no prātiem dubļus noskalo<br>un grēka važas atraisi,<br>lai noziedzība izbeigtos.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_4 = '<p class="psalms1">Lūk, ugunīga saule lec,<br>tā raisa grēku nožēlu –<br>jo dienas gaisma parāda,<br>cik pretīgs noziedzības ceļš.</p><p class="psalms2">Lai izzūd aklums mānīgais,<br>kas ilgu laiku vadīja<br>mūs grēka ceļos greizajos<br>un mūsu spēkus izšķieda.</p><p class="psalms1">Lai skaidrību nes gaisma šī<br>un mūsu sirdis attīra,<br>no meliem liek mums atteikties<br>un neļauj tumsā atgriezties.</p><p class="psalms2">Lai dienu šo mēs pavadām<br>bez viltus vārdos, nodomos,<br>no ļauniem darbiem vairoties,<br>lai sevi nesamaitātu.</p><p class="psalms1">Par visiem rūpējoties, Dievs<br>no rīta līdz pat vakaram<br>no Debesīm mūs novēro<br>un mūsu darbus izvērtē.</p><p class="psalms2">Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_1_4 = '<p class="psalms1">Dievs Kungs Tu visuspēcīgais,<br>tos, kas no ūdens nākuši,<br>Tu daļu sūti atpakaļ,<br>bet daļu – debess plašumos,</p><p class="psalms2">Tu laidi zivis ūdeņos<br>un putnus – lidot debesīs,<br>no vienas sēklas cēlušies,<br>tie dzīvo vietās dažādās.</p><p class="psalms1">Kungs, savus kalpus stiprini,<br>kas Tavas Asins mazgāti,<br>lai nepadotos ļaunumam,<br>nedz nāves priekšā baidītos.</p><p class="psalms2">Lai grēks nevienu nepakļauj<br>un neapmāna lepnība,<br>lai mazdūšīgie nesalūzt<br>un pieceltie lai nepakrīt.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_5 = '<p class="psalms1">Ak, Kristu, debess godība<br>un ļaužu svētā cerība,<br>Tu Tēva viendzimušais Dēls,<br>kas dzimis šķīstai Jaunavai.</p><p class="psalms2">Dod spēku miesai piecelties,<br>lai mostas arī skaidrais prāts<br>un steidzas Dievu godināt,<br>par visu Viņam pateikties.</p><p class="psalms1">Lūk uzaust možais auseklis,<br>kas vēsta gaismu atnākam,<br>nakts tumsa strauji atkāpjas,<br>lai svētums ļaudis apgaismo</p><p class="psalms2">un, mūsu prātus pārņemot,<br>tas aizdzen nakti garīgo,<br>kā arī sirdis tīras mums<br>līdz laiku beigām nosargā.</p><p class="psalms1">Kungs, vairo mūsu ticību –<br>kā pirmo to mums dāvāji,<br>lai cerība tai līdzi aug –<br>kļūs mīlestība stiprāka.</p><p class="psalms2">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_1_5 = '<p class="psalms1">Dievs, ļaužu saimes Radītāj,<br>kas viens pats visu pārvaldot,<br>reiz liki rasties pasaulē<br>it visu sugu dzīvniekiem.</p><p class="psalms2">Ar teikto vārdu dzīvību<br>pat lielām būtnēm iedvesi<br>un noteici Tu kārtību,<br>ka viss ir pakļauts cilvēkam.</p><p class="psalms1">Kungs, savus kalpus – ticīgos<br>no nešķīstības pasargā,<br>lai tikumus tā nemaitā<br>nedz arī darbus sabojā.</p><p class="psalms2">Ar prieku, lūdzam, piepildi<br>un žēlastību dāvini,<br>no nesaskaņām atbrīvo<br>un sadraudzību stiprini.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_1_6 = '<p class="psalms1">Jau pamalē mirdz rītausma,<br>pār zemi diena nolaižas,<br>ar gaismas šķēpu izgaiņā<br>it visus māņus riebīgos.</p><p class="psalms2">Lai tumsas maldi atkāpjas<br>un grēka tieksmes norimstas,<br>lai visas briesmas izbeidzas,<br>kas naktī nomocīja mūs.</p><p class="psalms1">Rīts pēdējais, kad pienāks reiz,<br>ko pazemīgi gaidām mēs,<br>lai Debess gaismā ieved mūs,<br>mums līksmi dziedot himnu šo.</p><p class="psalms2">Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';

// Parastā liturģiskā laika 2. un 4.ned. himnas
var hinmaVesperes_2_6 = '<p class="psalms1">Dievs, visu lietu Radītāj,<br>ar saviem darbiem daudzajiem<br>Tu piepildīji pasauli<br>ar neskaitāmām dāvanām.</p><p class="psalms2">Kad lielo darbu pabeidzi,<br>Tu apstājies un atpūties,<br>lai mēs, no Tevis mācoties,<br>pēc darba prastu atgūties.</p><p class="psalms1">Dod mirstīgajiem sapratni<br>no dzīves grēkā atteikties,<br>bet tikumībai tuvoties<br>un savu dzīvi veltīt Tev,</p><p class="psalms2">lai tiesas dienā lielajā,<br>kad šausmas pārņems pasauli,<br>mēs tomēr spētu priecāties,<br>jo miers Tavs sirdis piepilda.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
var hinmaLaudes_2_0 = '<p class="psalms1">Zūd melnā nakts un atnāk jauna diena,<br>pamalē sārta aust jau rīta blāzma:<br>steigsimies visi slavas dziesmām godāt<br>vareno Dievu.</p><p class="psalms2">Lai Dievs mums lielā žēlsirdībā visu<br>nemieru aizdzen, veselību dāvā,<br>lielajā savā Tēva mīlestībā<br>velk mūs pie sevis.</p><p class="psalms1">To lai mums dāvā Dieva varenība,<br>kas piemīt Tēvam, Dēlam, Garam Svētam,<br>godina kuru ticīgie ar dziesmām<br>pasaulē visā. Āmen.</p>';
var hinmaVesperes_2_0 = '<p class="psalms1">Ak, Gaisma, Trīsvienīgais Dievs<br>un Vienotība mūžīgā,<br>jau ugunīgā saule riet –<br>nāc sirdīs gaismu ielej mums.</p><p class="psalms2">No rīta gribam Tevi teikt,<br>gan pielūgt Tevi vakarā:<br>lai cauri visiem gadsimtiem<br>skan mūsu slavas dziesmas Tev!</p><p class="psalms1">Nu Tēvu, Dēlu lūdzam mēs,<br>un Garu, kas no Viņiem nāk:<br>Viens Trīsvienībā, Varenais,<br>tos stiprini, kas Tevi lūdz. Āmen.</p>';

var hinmaLaudes_2_1 = '<p class="psalms1">Ak, spožais gaismas dāvātāj,<br>ar saviem stariem spodrajiem<br>pēc nakts, kas nedrošību dveš,<br>Tu jaunā dienā ieved mūs.</p><p class="psalms2">Tu gaismas nesējs patiesais<br>un nevis debess ķermenis,<br>kas, jaunai dienai atnākot,<br>spīd blāvi debess pamalē.</p><p class="psalms1">Par sauli spožāks esi Tu,<br>pats esi gaišā diena mums,<br>kas mūsu dvēs’les cietoksnī<br>lej gaismu visās istabās.</p><p class="psalms2">Lai šķīstība gūst virsroku<br>pār visām miesas iekārēm,<br>un Svētais Gars lai piepilda<br>šo templi Dievam veltīto.</p><p class="psalms1">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_2_1 = '<p class="psalms1">Pirmsākums visai patiesajai gaismai,<br>uzklausi mūsu pazemīgās lūgsnas,<br>gaismu, kas aizdzen visu grēka tumsu,<br>sūti mums talkā.</p><p class="psalms2">Pabeigti jau ir dienas darbi visi,<br>kurus mēs veicām Tevis atbalstīti:<br>steidzam Tev izteikt pateicību savu<br>tagad un vienmēr.</p><p class="psalms1">Norietot saulei, atgriezties steidz krēsla:<br>lūdzam lai gaismu atsūta mums Saule,<br>kura ar saviem stariem  silda visus<br>eņģeļu pulkus.</p><p class="psalms2">Grēkus, kas sirdij uzgūluši šodien,<br>nomazgā, Kristu, mūsu miera Ķēniņ,<br>tīra un spoža lai mirdz visu nakti<br>dvēsele mūsu.</p><p class="psalms1">Slavu un godu dodam Dievam Tēvam,<br>Dēlam un Garam arī līdzvērtīgu,<br>kopā Tie valda jau no laiku gala<br>pasauli visu. Āmen.</p>';

var hinmaLaudes_2_2 = '<p class="psalms1">Ak, gaismas devēj mūžīgais,<br>pats esi gaišā diena Tu –<br>bez mitas gaismu dāvā mums,<br>ko tumsa nespēj sabojāt.</p><p class="psalms2">Nu atkāpjas nakts dziestošā,<br>tā jaunai dienai ceļu dod,<br>un, zvaigžņu gaismu pārspējot,<br>ir klāt jau spožais auseklis.</p><p class="psalms1">Mēs ceļamies no guļvietām<br>un priekā pateicamies Tev,<br>ka, nakti projām aizraidot,<br>nes saule jaunu dienu mums.</p><p class="psalms2">To lūdzam tagad, svētais Dievs,<br>lai mūsu prātus neuzveic,<br>nedz miesas dullās iegribas,<br>nedz pasaulīgās grūtības.</p><p class="psalms1">Lai dusmas spējam savaldīt<br>un nekalpojam vēderam,<br>no mantkārības vairāmies,<br>kā arī liekas greznības.</p><p class="psalms2">Lai prāts ir skaidrs, nelokāms<br>un miesa sargā šķīstību,<br>gars uzticību saglabā<br>un Kristus šodien vada mūs.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
var hinmaVesperes_2_2 = '<p class="psalms1">Ak, laiku Valdniek, Radītāj,<br>Tu darbiem dienas vēlēji,<br>bet naktis miegam, atpūtai –<br>tā Tevis dotā kārtība.</p><p class="psalms2">Jel sargā dvēs’les šķīstību,<br>lai ienaidnieks nakts klusumā<br>ar savām bultām indīgām<br>mums sirdi neievainotu.</p><p class="psalms1">Lai prāts ir brīvs no kaislībām<br>un nežēlīgām iegribām,<br>kas aptumšo mums saprātu<br>un gribasspēku vājina.</p><p class="psalms2">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_2_3 = '<p class="psalms1">Ir debess zilgmes Radītājs<br>mums devis tādu kārtību,<br>lai mēness gaismu naktī dod,<br>bet saule dienu izgaismo.</p><p class="psalms2">Nakts tumšā projām atkāpjas<br>un zeme gaismā ietērpjas,<br>jau prāts ir spēkus atguvis,<br>lai kaut ko labu paveiktu.</p><p class="psalms1">Mūs dziesmām slavēt Tevi, Dievs,<br>nu jaunā diena aicina,<br>un debess labvēlīgais smaids,<br>lai mūsu sirdis apskaidro.</p><p class="psalms2">No viltus gribam vairīties<br>un takām, kas uz ļaunu ved,<br>lai sevi neaptraipītu<br>mēs darbiem, runām netīrām.</p><p class="psalms1">Kad saule dienu piepildīs,<br>lai stiprina mūs ticība,<br>uz priekšu lai ved cerība<br>pie Kristus – mīlestība sien.</p><p class="psalms2">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
var hinmaVesperes_2_3 = '<p class="psalms1">Lūk, saule, lēnām norietot,<br>no kalniem, laukiem, ūdeņiem<br>ar lielām skumjām atvadās,<br>lai rītā atkal atgrieztos.</p><p class="psalms2">Ar sajūsmu mēs mirstīgie<br>uz Taviem darbiem raugāmies,<br>cik brīnišķīgi, Radītāj,<br>Tu visu esi kārtojis.</p><p class="psalms1">Un kamēr nakts tin klusumā<br>it visu plašo apkārtni,<br>kad darba duna apstājas<br>un visi steidzam atpūsties,</p><p class="psalms2">lai ticība un cerība<br>ar Tavu gaismu priecē mūs,<br>Vārds, atspulgs Tēva godībai,<br>to lūdzam Tev mēs, Mūžīgais.</p><p class="psalms1">Tu Saule nenorietošā,<br>kas spīdi mums bez apstājas,<br>pēc Tevis zeme ilgojas,<br>Tev slavu skandē debesis.</p><p class="psalms2">Tēvs ļauj mums kādreiz priecāties<br>par gaismu šo bez apstājas,<br>kad Tevi dziesmām godāsim<br>ar Dēlu, Garu mūžībā. Āmen.</p>';

var hinmaLaudes_2_4 = '<p class="psalms1">Jau dienas gaisma uzausa –<br>nu Dievu lūdzam bijīgi,<br>lai visās dienas nodarbēs<br>no ļauna Viņš mūs pasargā.</p><p class="psalms2">Lai mūsu mēli savalda,<br>ka strīdos neiesaistās tā,<br>un sargā mūsu skatienu,<br>lai tukšības tas nekāro.</p><p class="psalms1">Lai šķīsti siržu nodomi,<br>bēg projām trakās iegribas,<br>un mērenība pārtikā,<br>lai augstprātību apvalda.</p><p class="psalms2">Lai tad, kad beigsies diena šī<br>un nakts pie durvīm pieklauvēs,<br>mēs tīrām sirdīm varētu<br>ar dziesmām Tevi godināt.</p><p class="psalms1">Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaVesperes_2_4 = '<p class="psalms1">Dievs Kungs, Tu gaismā mirdzošā<br>šo dienu biji ietērpis,<br>nu, dienas gaismai nodziestot,<br>mēs Tevi dziesmām godinām.</p><p class="psalms2">Jau atkal vakars tuvojas<br>un lēnām pienāk saules riets,<br>drīz tumsa zemi sagūstīs –<br>viss seko savai kārtībai.</p><p class="psalms1">Bet Tu, visaugstais, svētais Dievs,<br>jel savus kalpus uzklausi,<br>kas dienas darbos guruši,<br>lai tumsība mūs nenomāc;</p><p class="psalms2">lai tumsa prātus nepārņem,<br>kad diena aiziet laicīgā,<br>bet Tava žēlastība dod,<br>ka redzam gaismu mūžīgo.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';

var hinmaLaudes_2_5 = '<p class="psalms1">Dievs – debess Gaisma mirdzošā<br>un visas gaismas Radītāj,<br>Tu izveidoji visumu<br>un arī pats to uzturi.</p><p class="psalms2">Ar savu dvesmu iesārto<br>jau zvaigznes nodzēš rītausma<br>un drēgnu vēju atsūta,<br>kas zemi rasā nomazgā.</p><p class="psalms1">Nakts ēna tagad projām bēg,<br>aiz sevis miglu atstājot,<br>un Kristus simbols – auseklis<br>no miega jauno dienu ceļ.</p><p class="psalms2">Dievs, diena Tu mums gaišākā,<br>Tu – gaisma pats un gaismeklis,<br>Tu Viens – par visiem varenāks<br>un varens Trīsvienībā viens.</p><p class="psalms1">Mēs Tevi lūdzam, Pestītāj,<br>un Tev mēs godu atdodam,<br>mēs savas balsis vienojam,<br>lai Tēvu, Garu slavētu. Āmen.</p>';
var hinmaVesperes_2_5 = '<p class="psalms1">Beidz diena savu skrējienu<br>un vakarstundā apstājas,<br>dot Dievam to, kas pienākas,<br>ar dziesmu tagad steidzamies.</p><p class="psalms2">Ir dienas darbi beigušies,<br>ko Kristu uzticēji mums,<br>dod vīnadārza strādniekiem<br>to godību, ko solīji.</p><p class="psalms1">Mūs strādāt tagad aicini<br>un algu soli nākotnē,<br>mums darbos, lūdzu, palīdzi,<br>pēc smagām pūlēm spirdzini.</p><p class="psalms2">Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var hinmaLaudes_2_6 = '<p class="psalms1">Skat, jauna diena uzausa,<br>mēs pateicībā priecīgi<br>nu Dievu dziedot godāsim,<br>to žēlastību cildinot,</p><p class="psalms2">ar kuru visa Radītājs<br>ir dienu, nakti veidojis<br>un vienai otru nomainīt<br>uz mūžiem strikti noteicis.</p><p class="psalms1">Tu īstā gaisma ticīgiem,<br>kas pāri dabas likumiem,<br>bez rieta un bez rītausmas<br>ar liesmu mūžīgu mums deg.</p><p class="psalms2">Tēvs mūžīgais, mums dāvā to,<br>ka varētu mēs dienu šo<br>ar Svētā Gara palīgu<br>par godu Kristum nodzīvot. Āmen.</p>';
}

{// Parastā laika Dienas stundu himnas
var hinmaDienas_3 = '<p class="psalms1">Nāc, Svētais Gars, kas dāvāts mums,<br>ar Tēvu, Dēlu vienots Tu.<br>Nāc, mūsu sirdīs iemājo<br>ar žēlastību piepildi.</p><p class="psalms2">Lai vārdi, domas, gribasspēks<br>Tev pateicības dziesmu dzied.<br>Lai mīlestība deg kā guns<br>un sasniedz arī tuvāko.</p><p class="psalms1">Mums Tēvu saprast palīdzi<br>kā arī Dēlu iepazīt,<br>Tev, Garam, kas no Abiem nāc,<br>uz visiem laikiem ticam mēs. Āmen.</p>';
var hinmaDienas_6 = '<p class="psalms1">Tu vadi, Dievs, visspēcīgi<br>šīs dienas gaitas dažādās,<br>Tu rītam maigu gaismu dod<br>un spožu sauli pusdienai.</p><p class="psalms2">Kungs, slāpē visas kaislības<br>un karstos strīdus atdzesē;<br>Tēvs, garu, miesu atjauno,<br>dod vienotību, mieru mums.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
var hinmaDienas_9 = '<p class="psalms1">Tu visas pasaul’s Radītāj,<br>cik liela Tava godība;<br>Tu saviem bērniem vienmēr dod<br>tik to, kas tiem par labu nāk.</p><p class="psalms2">Tu mūsu rokām uztici,<br>lai sargājam, kas Tevis dots;<br>dod mūsu darbiem augļus Tu<br>un mieru visai pasaulei.</p><p class="psalms1">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
var hinmaDienas_3_2 = "<p class='psalms1'>Kā piedien stundā trešajā,<br>nu tīrām sirdīm lūgsimies<br>mēs Trīsvienību vareno,<br>To dievbijīgi godinot,</p><p class='psalms2'>lai kļūtu mēs par mājokli<br>tam pašam Garam Svētajam,<br>kas apustuļiem sendienās<br>šai stundā tika atsūtīts.</p><p class='psalms1'>Ir debess laimes Radītājs<br>tik brīnišķīgā kārtībā<br>it visu skaisti veidojis,<br>lai mūžību mēs sasniegtu.</p><p class='psalms2'>Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>";
var hinmaDienas_6_2 = "<p class='psalms1'>Nu Kungu dziesmām slavēsim,<br>ar sirdi tīru, dedzīgu,<br>jo sestā stunda ir jau klāt<br>un lūgties visus aicina.</p><p class='psalms2'>Šai stundā visiem ticīgiem<br>pats Dieva Jērs ar upuri<br>un savu krusta uzvaru<br>reiz pestīšanu dāvāja.</p><p class='psalms1'>Šo Viņa gaismu spožāko,<br>kas visas ēnas aizgaiņā,<br>nu savās sirdīs laidīsim<br>lai žēlastību saņemtu.</p><p class='psalms2'>Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>";
var hinmaDienas_9_2 = "<p class='psalms1'>Lūk, savā labvēlībā Kungs<br>jau stundu devīto mums dod,<br>lai Trīsvienību vareno<br>mēs dievbijīgi godinām.</p><p class='psalms2'>Mēs noslēpumu dievišķo<br>nu tīrās sirdīs glabājot,<br>kā Pēteris mūs mācījis<br>pa pestīšanas ceļu iet,</p><p class='psalms1'>nu Dievu dziesmām godāsim,<br>pie apustuļiem tveroties,<br>lai mūsu vājie locekļi<br>tiek Kristus  spēka pildīti.</p><p class='psalms2'>Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>";
}

{// Adventa himnas
var himnaAdventsLaudes = "<p class='psalms1'>Klau, atskan Jāņa pērkonbalss,<br>kas tumsas darbus pārmet mums:<br>jel celieties no miega jūs –<br>skat, Kristus atmirdz debesīs.</p><p class='psalms2'>Lai mostas vienaldzīgais prāts,<br>kas sliktās domās iegrimis;<br>lūk, jauna zvaigzne uzausa,<br>lai grēka vainu noņemtu.</p><p class='psalms1'>No debesīm nāk Dieva Jērs,<br>uz sevis visus grēkus ņem.<br>Uz Viņu skatu paceļam<br>un lūdzam piedošanu mēs.</p><p class='psalms2'>Kad otrreiz atkal atnāks Viņš,<br>tad šausmas pārņems pasauli,<br>bet ticīgos Viņš netiesās<br>un savā aizsardzībā ņems.</p><p class='psalms1'>Lai Tēvam visuaugstajam<br>un Viņa Dēlam gods tiek dots,<br>kā arī Garam Svētajam<br>caur visiem laikiem mūžīgi. Āmen.</p>";
var himnaAdventsVesperes = "<p class='psalms1'>Dievs, debess zvaigžņu Radītāj<br>un Gaisma visiem ticīgiem,<br>Kungs Kristu, mūsu Pestītāj,<br>jel mūsu lūgsnas uzklausi.</p><p class='psalms2'>Tu līdzi jūtot cilvēcei,<br>kas nāves varai padota,<br>no posta glābi pasauli,<br>mums žēlastību dāvāji.</p><p class='psalms1'>Kad vakars zemi pārklāja,<br>no Karalienes – Jaunavas<br>Tu ienāci šai pasaulē<br>kā Līgavainis gaidītais.</p><p class='psalms2'>Gan eņģeļi, gan cilvēki –<br>mēs Tavai varai padoti<br>un ceļos krītot atzīstam:<br>Tu Ķēniņš visuaugstākais.</p><p class='psalms1'>Mēs lūdzam Tevi, Svētais Dievs,<br>kas nāksi tiesāt pasauli,<br>ikkatru brīdi sargā mūs<br>no ienaidnieka viltībām.</p><p class='psalms2'>Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>";

// Adventa himnas sākot ar 17.decembri
var himnaAdventsLaudes17 = "<p class='psalms1'>Sauc skaļā balsī pravieši,<br>ka drīz pie mums būs Mesija,<br>pa ceļu, Dieva šķīstītu,<br>nāk pestīšana visiem mums.</p><p class='psalms2'>Lūk, tāpēc gaišāks kļūst mums rīts<br>un sirdis priekā gavilē,<br>jo uzticama ziņa šī,<br>kas vēstī Dieva godību.</p><p class='psalms1'>Kad pirmoreiz Viņš ieradās,<br>tad nenāca, lai sodītu,<br>bet nāca brūces sadziedēt<br>un izglābt postā grimstošos.</p><p class='psalms2'>Kad ieradīsies otrreiz Viņš,<br>mums visiem jābūt gataviem<br>pie durvīm Kristu sagaidīt,<br>lai goda kroni saņemtu.</p><p class='psalms1'>Tad spoža gaisma atspīdēs<br>un mūžība mūs apskaidros.<br>Tad visi sapratīsim mēs,<br>ka Dieva tiesa sākusies.</p><p class='psalms2'>Mēs Kristu Tevi meklējam,<br>jo atzīstam, ka esi Dievs,<br>kaut varētu mēs mūžībā<br>ar slavas dziesmām Tevi teikt. Āmen.</p>";

var himnaAdventsVesperes17 = "<p class='psalms1'>To Vārdu, kas nes glābiņu,<br>ko Tēvs uz zemi sūtīja,<br>jel savās miesās pieņem Tu,<br>ak, Marij, šķīstā Jaunava.</p><p class='psalms2'>Visaugstā spēks pār Tevi nāk,<br>Gars Dzīvinātājs apēno,<br>lai Kungu – Kristu ieņemtu,<br>kas Tēvam Dēls ir līdzvērtīgs.</p><p class='psalms1'>Šīs svētās durvis stingri stāv<br>un modri sargā svētnīcu,<br>vien Valdniekam visaugstākam<br>pa viņām ieiet atļauts ir.</p><p class='psalms2'>Reiz praviešiem Viņš apsolīts,<br>nu Gabriēla pavēstīts,<br>pirms rīta ausmas piedzimis,<br>Kungs Kristus pie mums visiem nāk.</p><p class='psalms1'>Jau līksmo visi eņģeļi<br>un ļaudis priekā gavilē,<br>jo Diženais nāk pazemīgs,<br>lai glābtu to, kas pazudis.</p><p class='psalms2'>Tev, Kristu, Ķēniņ svētākais,<br>un Tēvam vienmēr gods lai skan<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>";

var himnaAdventsDienas3 = hinmaDienas_3_2;
var himnaAdventsDienas6 = hinmaDienas_6_2;
var himnaAdventsDienas9 = hinmaDienas_9_2;

// ===================
}

{// ZIEMMASVĒTKU himnas
var himnaZiemassvetkiLaudes = "<p class='psalms1'>No saules lēkta austrumos<br>pa visu plašo pasauli<br>mēs dziedam Kristum valdniekam,<br>kas Marijai ir piedzimis.</p><p class='psalms2'>Pats visu lietu veidotājs<br>ir kalpa miesā ietērpies,<br>lai miesā miesu izglābjot,<br>Viņš nezaudētu radīto.</p><p class='psalms1'>Lūk, Mātes miesās svētajās<br>nu ienāk debess svētība, –<br>nes savā klēpī jaunava<br>to brīnumu, ko neaptver.</p><p class='psalms2'>Visšķīstās dvēs’les mājoklis<br>nu kļūst par Dieva svētnīcu;<br>Tā vīra miesas neskarta,<br>no Gara Dēlu ieņēma.</p><p class='psalms1'>Jau Mātei Bērns ir piedzimis,<br>ko pavēstīja Gabriēls,<br>ko atpazina Kristītājs,<br>kad mātes miesās bija slēgts.</p><p class='psalms2'>To sienā gulēt nolika,<br>Viņš nevairījās silītes,<br>un Tas, kas visus pamielo,<br>kā bērns ar pienu barots tiek.</p><p class='psalms1'>Nu Debess kori priecājas,<br>dzied Dievam slavu eņģeļi,<br>un ganiem pirmiem atklājas,<br>tas Gans, kas visu radījis.</p><p class='psalms2'>Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>";
var himnaZiemassvetkiVesperes = "<p class='psalms1'>Ak, Kristu, visu atpircēj,<br>Tu Tēva viendzimušais Dēls,<br>no Tēva klēpja brīnišķi<br>pirms visiem mūžiem dzemdināts.</p><p class='psalms2'>Tu gaisma, Tēva diženums<br>un visu ļaužu cerība,<br>jel mūsu lūgsnas uzklausi,<br>ko Tavi kalpi izsaka.</p><p class='psalms1'>Ak, Pestītāj, jel atceries,<br>ka mūsu vājo ķermeni<br>no nevainīgās Jaunavas<br>Tu piedzimstot reiz pieņēmi.</p><p class='psalms2'>Šie svētki šodien liecina,<br>ko katru gadu svinam mēs,<br>ka, Tēva troni atstājis,<br>Tu nāci pestīt pasauli.</p><p class='psalms1'>Lai debess, zeme, ūdeņi<br>un visi, kas tur mitinās,<br>ar gaviļdziesmu Tēvu sveic,<br>kas Tevi atsūtīja mums.</p><p class='psalms2'>Mēs arī, kurus atpirki<br>ar savām svētām asinīm,<br>Tev jaunu himnu skandinām,<br>kad svinam Tavu Dzimšanu.</p><p class='psalms1'>Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>";
var himnaZiemassvetkiLaudes6jan = "<p class='psalms1'>Ikviens, kas Kristu meklējat,<br>uz augšu acis paceliet:<br>tur zīmi varat ieraudzīt,<br>kas rāda Kunga godību.</p><p class='psalms2'>Šī zvaigzne, kas ir spožāka<br>un skaistāka par sauli pat,<br>ir atnākusi pavēstīt,<br>Dievs iemiesojies, nāk pie mums.</p><p class='psalms1'>Pat tālās zemēs austrumos,<br>kur saule rītos parādās,<br>tur gudrie, tulki zinoši,<br>šo ķēniņzīmi atpazīst.</p><p class='psalms2'>“Kas ir šis valdnieks, – brīnās tie –<br>tik varens zvaigžņu pavēlnieks,<br>tam debess pulki pakļaujas,<br>ikviena gaisma pakalpo?</p><p class='psalms1'>Šis Spīdeklis, ko vērojam,<br>kas spīdēt nekad nepārstās,<br>tik cildens, dižens, bezgalīgs<br>un senāks ir par pasauli.</p><p class='psalms2'>Viņš valdnieks visiem pagāniem<br>un jūdu tautas karalis,<br>jau Abrahamam apsolīts<br>kā atvase uz mūžību.”</p><p class='psalms1'>Tev, Jēzu, vienmēr gods lai skan,<br>kas tautām tagad atklājies,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>";
var himnaZiemassvetkiVesperes6jan = "<p class='psalms1'>Tu, Herod, ļaunais ienaidniek,<br>ko bīsties Kristu atnākam?<br>Tas negrib varu laicīgo,<br>kas dāvā debess valstību.</p><p class='psalms2'>Iet gudrie, zvaigznei sekojot,<br>ar lāpām tumsu kliedējot,<br>lai rastu Gaismu patieso<br>un Dievu veltēm godātu.</p><p class='psalms1'>Ar kristību nu Dieva Jērs<br>ir svētdarījis ūdeņus, –<br>bez grēka Viņš, mūs nomazgā,<br>lai pakritušus pieceltu.</p><p class='psalms2'>Šis jaunais spēks, tik brīnumains:<br>jau ūdens traukos sārtojas,<br>kas ieliets ir pēc pavēles,<br>par labu vīnu pārvēršas.</p><p class='psalms1'>Tev, Jēzu, vienmēr gods lai skan,<br>kas tautām tagad atklājies,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>";

var himnaNevainigieBerniniLaudes = " <p class='psalms1'>Te izdzird tirāns satrauktais,<br>Visaugstais ķēniņš ir jau klāt,<br>no Dāvida cilts nācis Viņš,<br>lai Izraēli valdītu.</p><p class='psalms2'>Tas brēkt sāk baiļu ārprātā:<br>“Viņš likumīgais, beigas mums!<br>Nu skrieniet, tveriet zobenus,<br>lai šūpuļi mirkst asinīs!”</p><p class='psalms1'>Kāds labums no šī slaktiņa?<br>Vai, Herod, tas tev līdzēja?<br>Tik daudziem vajadzēja mirt,<br>bet Bērniņš Jēzus izglābās.</p><p class='psalms2'>Mēs sveicam mazos mocekļus,<br>ko pašā dzīves sākumā<br>kā rozes tikko plaukušas<br>cērt Kristus ļaunais ienaidnieks.</p><p class='psalms1'>Jūs pirmais Kristus upuris,<br>jūs mazo jēru ganāmpulks,<br>kas goda drānās ietērpti<br>nu Dieva namā spēlējas.</p><p class='psalms2'>Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>";
}

{// GAVĒŅA himnas
var himnaGavenisLaudes = '<p class="psalms1">Jau, Kristu, Saule patiesā,<br>sāk izklīst tumsa nelabā,<br>kad Tu nāc zemi apgaismot,<br>lai tikumība atgrieztos.</p><p class="psalms2">Tu laiku labvēlīgu dod<br>un sirdīs ielej nožēlu,<br>lai labestība atgriež tos,<br>ko žēlsirdība saudzēja;</p><p class="psalms1">un tos, kas grēkus nožēlo,<br>no vainas nastas atbrīvo,<br>jo Žēlsirdība lielāka<br>par grēku nastas smagumu.</p><p class="psalms2">Nāk diena, diena Tavējā,<br>kas visam atkal uzplaukt liks;<br>un tāpēc tajā līksmosim<br>par žēlastību, ko Tu dod.</p><p class="psalms1">Ak, Trīsvienība, gādīgā,<br>ko pielūdz Visums radītais,<br>un mēs, kam esi piedevis,<br>Tev jaunu dziesmu skandinām. Āmen.</p>';

var himnaGavenisLaudesSv = '<p class="psalms1">Ar galvām zemu noliektām<br>ikviens no sirds mēs lūdzamies<br>un savas vainas apraudam,<br>lai soda dusmas novērstu.</p><p class="psalms2">Ar saviem grēkiem kaitinām<br>mēs Tavu labestību, Dievs.<br>No debesīm, Kungs žēlīgais,<br>mums piedošanu atsūti.</p><p class="psalms1">Un piemini, ka esam mēs,<br>kaut vāji, Tavas radības.<br>Jel palīdzi mums rīkoties<br>un Tavu vārdu godā celt.</p><p class="psalms2">Dzēs ļaunumu, ko izdarām,<br>un vairo sekmes labajā,<br>lai kļūtu patīkami mēs<br>Tev šeit un arī mūžībā.</p><p class="psalms1">Jel dari, Trīsvienīgais Dievs,<br>viens Vienotībā svētajā,<br>ka Taviem ļaudīm augļus nes<br>šie atturības upuri. Āmen.</p>';

var himnaGavenisDienas3 = '<p class="psalms1">Ar ticību, ko dzīvojam,<br>ar pastāvīgu cerību,<br>ar mīlestību saņemto,<br>mēs Kristu dziesmās godinām.</p><p class="psalms2">Šai dienas stundā veda To,<br>lai Viņš pie krusta nomirtu;<br>un, nesot rīku briesmīgo,<br>Kungs izglābj avi klīstošo.</p><p class="psalms1">Lūk, tāpēc Kungu lūgsimies,<br>kas mūs ir brīvus darījis,<br>lai izrauj tos no pasaules,<br>no parāda kas atpirkti.</p><p class="psalms2">Nu Tēvu, Dēlu lūdzam mēs<br>un Garu, kas no Viņiem nāk:<br>Viens Trīsvienībā, Varenais,<br>tos stiprini, kas Tevi lūdz. Āmen.</p>';
var himnaGavenisDienas6 = '<p class="psalms1">Šai stundā Kristus izslāpis,<br>uz pleciem krustu cēla Viņš;<br>Kungs, tiem, kas Tevi dziesmās teic,<br>pēc taisnīguma izslāpt liec.</p><p class="psalms2">Kā arī izsalkumu dod<br>pēc Tevis dotās barības,<br>lai riebjas viņiem noziegums<br>un tikumību godā ceļ.</p><p class="psalms1">Lai Svētā Gara iedvesma<br>tā pārņem visus dziedošos,<br>ka rimstas miesas iegribas<br>un kūtrā galva pamostas.</p><p class="psalms2">Nu Tēvu, Dēlu lūdzam mēs<br>un Garu, kas no Viņiem nāk:<br>Viens Trīsvienībā, Varenais,<br>tos stiprini, kas Tevi lūdz. Āmen.</p>';
var himnaGavenisDienas9 = '<p class="psalms1">Jau dienas stunda devītā<br>mūs Dievu slavēt aicina,<br>lai Jēzus vārdā svētajā<br>mēs piedošanu saņemtu.</p><p class="psalms2">Lūk, grēkus atzīst ļaundaris<br>un saņem Kristus glābiņu,<br>lai gods, ko Dievam atdodam,<br>no soda dara brīvus mūs.</p><p class="psalms1">Ar krustu nāve uzveikta,<br>pēc tumsas gaisma atausa;<br>tiek grēka vara sagrauta,<br>lai spožums prātus apskaidro.</p><p class="psalms2">Nu Tēvu, Dēlu lūdzam mēs<br>un Garu, kas no Viņiem nāk:<br>Viens Trīsvienībā, Varenais,<br>tos stiprini, kas Tevi lūdz. Āmen.</p>';

var himnaGavenisVesperes = '<p class="psalms1">Tu, Jēzu, devi gavēni,<br>lai četr(u)desmit dienas mēs<br>nu atturībā dzīvotu<br>un savas sirdis dziedētu.</p><p class="psalms2">Nāc, palīgā, Dievs, Baznīcai<br>un tiem, kas vainas nožēlo, –<br>mēs lūdzam galvām noliektām, –<br>no grēkiem visus attīri.</p><p class="psalms1">Jel piedošanu dāvā mums<br>par grēkiem, kas reiz darīti,<br>un labvēlīgi palīdzi<br>no tiem mums izbēgt nākotnē.</p><p class="psalms2">Par savām vainām gandarām<br>un apņemamies laboties,<br>lai varētu mēs cienīgi<br>tad Pashas svētkos līksmoties.</p><p class="psalms1">Ak, Trīsvienība, gādīgā,<br>ko pielūdz Visums radītais,<br>un mēs, kam esi piedevis,<br>Tev jaunu dziesmu skandinām. Āmen.</p>';

var himnaGavenisVesperesSv = '<p class="psalms1">Dievs, mūsu labais Radītāj,<br>no sirds mēs Tevi lūdzamies,<br>lai visiem tiek šis gavēnis<br>ar atturību svētdarīts.</p><p class="psalms2">Tu, kuram sirdis atklājas,<br>kas redzi mūsu vājumu,<br>sniedz piedošanu dāsni tiem,<br>kas savus grēkus nožēlo.</p><p class="psalms1">Tik bieži, Kungs, mēs grēkojam,<br>bet sargi tos, kas atzīstas,<br>un Tava vārda slavas dēļ,<br>jel dziedē ļaunā nomāktos.</p><p class="psalms2">Caur atturību palīdzi<br>no ārišķībām atteikties,<br>lai gavējot gars attīrīts<br>no ļaunā spētu vairīties.</p><p class="psalms1">Jel dari, Trīsvienīgais Dievs,<br>viens Vienotībā svētajā,<br>ka Taviem ļaudīm augļus nes<br>šie atturības upuri. Āmen.</p>';

// =====
var himnaKlusasDienas = '<p class="psalms1">Lai Dieva tauta gavilē<br>par pestīšanas uzvaru,<br>jo Jēzus, visu Pestītājs,<br>ir gāzis nāves valdnieku.</p><p class="psalms2">Nes rokās pūlis atvases<br>no palmām un no olīvām;<br>“Hosanna!” visi skaļi sauc:<br>“Tu Dāvidam dēls solītais!”</p><p class="psalms1">Nu steigsim visi sagaidīt<br>mēs Visuaugsto Valdnieku<br>un, slavas himnas skandinot,<br>Tam palmu zarus nesīsim.</p><p class="psalms2">Lai mūsu vārgos soļus Viņš<br>ar žēlastību atbalsta,<br>un pateicībā vienmēr mēs,<br>Tam dodam to, kas pienākas.</p><p class="psalms1">Lai Dievam Tēvam gods tiek dots<br>un Viņa Dēlam vienīgam<br>ar Svēto Garu, Aizstāvi,<br>uz visiem laikiem mūžīgi. Āmen.</p>';

var himnaKlusasLaudes = '<p class="psalms1">Skaties – spļāvieni un niedre,<br>etiķis, žults, naglas, šķēps;<br>viegli miesa pārdurta tiek<br>asins, ūdens ārā līst;<br>zeme, jūra, visums, zvaigznes<br>mazgāti šai straumē tiek!</p> <p class="psalms2">Uzticamais krusts, starp visiem<br>kokiem tu visdižākais!<br>Mežā it nevienā neplauks<br>tāda dzīva atvase.<br>Saldais koks, ar naglu saldo<br>saldo Nastu noturi!</p><p class="psalms1">Noliec zarus, koks tik augstais,<br>stiprā, plašā dvēsele,<br>un tad atmaigs saspringums tas,<br>kas tev dots no dzimšanas,<br>sevī maigi turēsi tu<br>augsto debess Ķēniņu.</p><p class="psalms2">Vienīgi tu biji cienīgs<br>turēt zemes Glābēju,<br>miera ostu sagatavot<br>pasaul’s kuģim satriektam,<br>ko no Jēra sāna līstot,<br>svētā asins slacīja.</p><p class="psalms1">Dievam Tēvam, Dievam Dēlam,<br>Garam Ielīksmotājam,<br>mūžīgs gods un slava lai skan<br>Trīsvienībai svētajai,<br>kas ar savu žēlastību<br>atpirka un sargā mūs. Āmen.</p>';
var himnaKlusasVesperes = '<p class="psalms1">Liek pacelt Ķēniņš karogu,<br>un atmirdz krusta noslēpums –<br>pats svētais miesas Radītājs<br>pie koka miesā pienaglots.</p><p class="psalms2">Tad nomocītā sānu vēl<br>ar aso šķēpu caurdūra,<br>un ūdens, asins izplūda,<br>lai mūs no grēkiem mazgātu.</p><p class="psalms1">Koks brīnišķais un mirdzošais,<br>un ietērpts karaļpurpurā<br>tiek izvēlēts par cienīgu,<br>lai svēto Miesu turētu.</p><p class="psalms2">Ak, laimīgais, kas turēji<br>uz zariem pasaul’s Glābēju, –<br>to samaksu, kas izrāva<br>no elles valgiem cilvēci.</p><p class="psalms1">Sveiks, altāri, sveiks, upuri,<br>kas svinat lielo godību,<br>kad Dzīve nāvi izcieta,<br>caur nāvi dzīvi atgrieza!</p><p class="psalms2">Krusts, cerība tu vienīgā<br>mums visās dzīves grūtībās,<br>jel vairo spēkus ticīgiem<br>un apsūdzēto vainas dzēs.</p><p class="psalms1">Lai Tevi, Trīsvienīgais Dievs,<br>nu slavē visas dvēseles, –<br>ar krusta noslēpumu tās<br>Tu vienmēr glāb un stiprini. Āmen.</p>';

var himnaPedejoVakarinuVesperes = '<p class="psalms1">Kunga nāve, tu mums dārgā piemiņā,<br>dzīvā maize, ļaudīm sniedz kas dzīvību,<br>dāvā manam prātam savu spirgtumu<br>un pēc tevis, saldās, vienmēr ilgoties!</p><p class="psalms2">Žēlsirdīgais Jēzu, labais pelikān,<br>Tava Asins svētā – pestīšana man.<br>Cik šī Asins dārga! Lāses pietiktu,<br>pasaulei lai visas vainas noņemtu.</p><p class="psalms1">Tevi uzlūkošu vaigu vaigā reiz<br>beidzot priecīgs redzot Tavu godību,<br>Tēvam, Tev un Garam slavas dziesmu tad<br>dziedāšu es svēto pulkam pievienots. Āmen.</p>';

himnaLielasPiektdienasDienas3 = '<p class="psalms1">Glāb, Atpestītāj, savu cēlo radību,<br>pēc Tava svētā vaiga tēla veidotu.<br>Neļauj, ka sātans saplosa to viltīgi,<br>par ko Tu savas nāves cenu maksāji.</p><p class="psalms2">Pažēlo savus kalpus, kas ir nebrīvē,<br>attaisno apsūdzētos, piecel kristušos,<br>un tiem, ko atpirki ar savām asinīm,<br>ļauj līksmot mūžīgi ar Tevi, Karali. Āmen.</p>';
himnaLielasPiektdienasDienas6 = '<p class="psalms1">Krusts, pasaulei tu svētība,<br>un cerība, drošs glābiņš ar’.<br>Reiz lāsta smagums biji tu,<br>uz debesīm nu durvis ver.</p><p class="psalms2">Tu turi tagad Hostiju,<br>kas visus mūs pie sevis velk.<br>Tai pasaul’s valdnieks uzbruka,<br>bet panākumus neguva.</p><p class="psalms1">Lai Tēvam, Tev un Aizstāvim<br>tiek, Jēzu, gods dots līdzvērtīgs<br>par krusta gūto uzvaru,<br>ko baudīt varam mūžīgi. Āmen.</p>';
himnaLielasPiektdienasDienas9 = '<p class="psalms1">Ar Krustu, Jēzu, lūdzam mēs,<br>tos ieved dzīvē patiesā,<br>ko krusta kokā pienaglots<br>Tu labvēlējies atpestīt.</p><p class="psalms2">Ar savu jauno Likumu<br>Tu atcel veco spriedumu –<br>nu izgaist senā verdzība<br>un atdzimst īstā brīvība.</p><p class="psalms1">Lai Tēvam, Tev un Aizstāvim<br>tiek, Jēzu, gods dots līdzvērtīgs<br>par krusta gūto uzvaru,<br>ko baudīt varam mūžīgi. Āmen.</p>';

himnaLielasSestdienasLaudes = '<p class="psalms1">Tev, visus mūs kas atpirki,<br>nu slavas dziesmu skandinām;<br>Kungs, piedod, lūdzu, piedod mums,<br>kas savus grēkus atzīstam.</p><p class="psalms2">Tu visus ļaunā ieročus<br>ar krusta nāvi satrieci,<br>un tāpēc krustu nesam mēs<br>kā savas dzīves karogu.</p><p class="psalms1">Kaut vienmēr Tu šo naidnieku<br>no mūsu dzīves triektu prom,<br>lai nespētu tas sagandēt<br>ar Tavām as’nīm atpirktos.</p><p class="psalms2">Un pazemē tad mūsu dēļ<br>Tu nokāpi pie mirušiem,<br>lai dotu dzīvi mūžīgo<br>tiem, kas ir nāves gūstekņi.</p><p class="psalms1">Laiks noliktais kad pienāks reiz<br>un beigas būs šai pasaulei,<br>ikvienam pēc tā nopelniem<br>Tu algu sniegsi taisnīgi.</p><p class="psalms2">Nu, Kristu, Tevi lūdzam mēs,<br>nāc, mūsu brūces dziedini,<br>ar Tēvu, Garu kopā Jums<br>mēs mūžam slavu skandēsim. Āmen.</p>';
himnaLielasSestdienasVesperes = '<p class="psalms1">Tu mūsu glābēj vienīgais<br>un Atpestītāj izcilais,<br>mums, Kristu, Ķēniņ, palīdzi<br>ar krustu vienmēr lepoties.</p><p class="psalms2">Ar nāvi nāvi sagraudams,<br>ar dzīvi dzīvi dāvādams,<br>Tu ļauno garu uzveici –<br>šo nāves kalpu viltīgo.</p><p class="psalms1">Ar mīlestību kapā likts,<br>Tu nokāpi pie mirušiem,<br>lai nāves vārtus atvērtu<br>un senčus laistu brīvībā.</p><p class="psalms2">Tu mirdzi, Svētais Upuri,<br>pie Tēva debess godībā,<br>tos uzklausi, kas atpirkti<br>ar Tavām dārgām asinīm.</p><p class="psalms1">Tev katru dienu sekojot,<br>lai augam savos tikumos,<br>un visas ļaunās kaislības<br>ar krusta zīmi uzveicam.</p><p class="psalms2">Lai Tēvam, Tev un Aizstāvim,<br>tiek, Jēzu, gods dots līdzvērtīgs,<br>par spožo krusta uzvaru,<br>ko baudīt varam mūžīgi. Āmen.</p>';
}

{// Dievam
var DievsSvetiLatviju = '<p class="psalms1">Dievs, svētī Latviju,<br>Mūs’ dārgo tēviju,<br>Svētī jel Latviju,<br>Ak, svētī jel to!</p><p class="psalms2">Kur latvju meitas zied,<br>Kur latvju dēli dzied,<br>Laid mums tur laimē diet,<br>Mūs’ Latvijā!</p>';

var VeniCreatorSpiritus = '<p class="psalms1">Nāc, Svētais Gars, Dievs Radītājs<br>Tu žēlastību dāvātājs.<br>Nāc, mājo mūsu dvēselēs,<br> lai Tavi bērni būtu mēs.</p><p class="psalms2">Par Aizstāvi Tu cildināts<br>un Dieva tautai dāvināts;<br>Tu dzīves ceļā gaismas stars,<br>dzīvs avots, mīlestības gars.</p><p class="psalms1">Ar septiņveida dāvanām,<br>vislabā Tēva sūtītām,<br>Tu savus ļaudis stiprini<br>un Dievu slavēt aicini.</p><p class="psalms2">No Tevis gaismu gribam lūgt<br>un Tavā mīlestībā būt.<br>Nāc, rādi ceļu cildeno<br>Uz dzīves mērķi augstāko.</p><p class="psalms1">Pret ļauno cīņā stiprini<br>un savu mieru dāvini,<br>mūs vadi, lai Tev sekojam<br>un debess laimi mantojam.</p><p class="psalms2">Mēs ticam Tēvam mūžīgam<br>un Dieva Dēlam vienīgam,<br>un Garam visusvētajam,<br>šai Trīsvienībai dievišķai. Āmen.</p>';// vecā versija, jaunā ir himnaLieldienasVesperes2

//var TeDeumLaudamus1 = '<p class="psalms1">Tevi, Dievs, mēs slavējam,* Tevi, Kungu, augsti teicam.<br>Tevi, mūžīgo Tēvu,* visa zeme godina.<br>Tevi visi eņģeļi,* Tevi Debesis un visi tās spēki,<br>Tevi ķerubi un serafi* nemitīgi daudzina:<br>Svēts, svēts, svēts ir Kungs,* debespulku Dievs!<br>Debesis un zeme* ir Tavas godības pilna.</p><p class="psalms2">Tevi slavē* cildenais apustuļu koris,<br>Tevi teic* cienījamie daudzie pravieši,<br>Tevi godina* mirdzošie mocekļu pulki.<br>Tevi visā pasaulē* sludina svētā Baznīca:<br>Tevi, bezgala diženo Tēvu,* Tavu godājamo, patieso un vienīgo Dēlu,<br>kā arī Svēto Garu,* Iepriecinātāju.</p><p class="psalms1">Tu, godības Karali,* Kristu,<br>Tu esi Tēva* mūžīgais Dēls.<br>Lai atbrīvotu cilvēku,* Tu nebaidījies iemiesoties Jaunavas klēpī.<br>Tu, salauzis nāves varu,* atvēri ticīgajiem debesu valstību.<br>Tu sēdi pie Dieva labās rokas* Tēva godībā.<br>Tu esi Tiesnesis,* kas atnāksi tiesāt pasauli.<br>Tādēļ, Tevi lūdzam, palīdzi saviem kalpiem,* kurus esi atpircis ar visdārgajām asinīm.<br>Pievieno mūs saviem svētajiem* mūžīgajā svētlaimē.</p>';

var TeDeumLaudamus = '<p class="psalms1">Tevi, Dievs, mēs slavējam,<br>Tevi, Kungu, augsti teicam.<br>Tevi, mūžīgo Tēvu,<br>visa zeme godina.</p><p class="psalms2">Tevi visi eņģeļi,<br>Tevi Debesis un visi tās spēki,<br>Tevi ķerubi un serafi<br>nemitīgi daudzina:</p><p class="psalms1">Svēts, svēts, svēts ir Kungs,<br>debespulku Dievs!<br>Debesis un zeme<br>ir Tavas godības pilna.</p><p class="psalms2">Tevi slavē cildenais apustuļu koris,<br>Tevi teic cienījamie daudzie pravieši,<br>Tevi godina mirdzošie mocekļu pulki.<br>Tevi visā pasaulē sludina svētā Baznīca:</p><p class="psalms1">Tevi, bezgala diženo Tēvu,<br>Tavu godājamo,<br>patieso un vienīgo Dēlu,<br>kā arī Svēto Garu, Iepriecinātāju.</p><p class="psalms2">Tu, godības Karali, Kristu,<br>Tu esi Tēva mūžīgais Dēls.<br>Lai atbrīvotu cilvēku,<br>Tu nebaidījies iemiesoties Jaunavas klēpī.</p><p class="psalms1">Tu, salauzis nāves varu,<br>atvēri ticīgajiem debesu valstību.<br>Tu sēdi pie Dieva labās rokas Tēva godībā.<br>Tu esi Tiesnesis, kas atnāksi tiesāt pasauli.</p><p class="psalms2">Tādēļ, Tevi lūdzam, palīdzi saviem kalpiem,<br>kurus esi atpircis ar savām dārgajām asinīm.<br>Pievieno mūs saviem svētajiem<br>mūžīgajā svētlaimē.</p>';
}

{//VSJ Marijas
// Marija, šķīstā Jaunava
var himnaMarijaLaudesSkista = '<p class="psalms1">Marija, šķīstā Jaunava,<br>Pestīšanas rītausma,<br>Mūsu līksmības cēlonis,<br>Baznīca tevi godina!</p><p class="psalms2">Dieva gribu pieņemot,<br>Tu kļuvi Kristus Māte.<br>Dēlam miesu dāvājot,<br>Dzemdēji Mistisko Miesu.</p><p class="psalms1">Kad Kristus mira uz krusta,<br>Lai vestu mūs pie Tēva,<br>Tu savā sirdī glabāji<br>Visas Baznīcas ticību.</p><p class="psalms2">Tu lūdzies kopā ar Baznīcu,<br>Kad Svētais Gars pār to nāca.<br>Tu Jēzus mācekļiem kļuvi,<br>Dieva labvēlības zīme.</p><p class="psalms1">Marija, ņem mūs savā gādībā,<br>Kas, vienoti mīlestībā,<br>Esam Kristus Miesas locekļi<br>Svētajā Baznīcā.</p><p class="psalms2">Tēvam un Dēlam, un Garam;<br>Gods lai un slava ir mūžam.<br>Baznīca rītausmas gaismā<br>Lai slavē savu Māti. Āmen.</p>';

var himnaMarijaLaudes = '<p class="psalms1">Ak, godināmā Valdniece<br>par visām zvaigznēm spožāka,<br>Tu to, kas Tevi radīja<br>ar svēto krūti zīdīji.</p><p class="psalms2">Tavs svētais Dēls to atgrieza,<br>ko Ievas lāsts mums atņēma.<br>Mums ceļu laipni parādi,<br>lai Debesīs mēs nokļūtu.</p><p class="psalms1">Tu durvis Debess Ķēniņam<br>un Gaismas vārti mirdzošie.<br>To Dzīvi, ko dod Jaunava,<br>nu atpestītie slavējiet.</p><p class="psalms2">Lai Tēvam, Garam Svētajam<br>un Tavam Dēlam gods tiek dots,<br>kas Tevi izrotājuši<br>ar žēlastības pilnību. Āmen.</p>';
var himnaMarijaPrezentacijaLaudes = '<p class="psalms1">Ak, Marij, svētā Jaunava,<br>pēc Dieva gudrā nodoma<br>Tu ķēniņmeita, līgava<br>jau pašā laiku sākumā.</p><p class="psalms2">Tu bezvainīgā Jaunava,<br>ko izredzēja debesis<br>par Dieva grezno mājokli<br>un, Garu sūtot, svētīja.</p><p class="psalms1">Tu mīlestības paraugs mums,<br>kas visu labo rādi mums,<br>Tu īstās gaismas iesākums,<br>kas Dieva sēklu sevī nes.</p><p class="psalms2">Visaugstā Dieva mājoklī<br>Tu svētā priekā līksmojies,<br>no Jesses celma atvase<br>ar žēlastību pildīta.</p><p class="psalms1">Ak pērle koši mirdzošā<br>un spožā zvaigzne pasaulei,<br>nāc, šķīstī mūsu tikumus,<br>par Gara tempļiem dari mūs.</p><p class="psalms2">Lai Trīsvienībai gods tiek dots,<br>ak dižciltīgā Jaunava,<br>kas Tevi ļaudīm dāvāja<br>kā žēlastību krātuvi. Āmen.</p>';

var himnaMarijaVesperesI = '<p class="psalms1">Tu, Marij, ļaužu lūgšanas<br>ar mīlestību uzklausi,<br>mēs Tevi lūdzam: pavadi<br>mūs visās dzīves grūtībās.</p><p class="psalms2">Jel palīdzi, kad smacē nost<br>mūs smagā vainas apziņa,<br>un važas, lūdzu, atraisi,<br>kas sirdi grēkam piesaista.</p><p class="psalms1">Steidz palīgā, ja vilina<br>mūs pasaulīgie mānekļi,<br>lai prāts no ceļa nenoklīst,<br>kas ved uz debess skaidrību.</p><p class="psalms2">Steidz palīgā, ja dzīvībai<br>sāk draudēt briesmas laicīgās,<br>mums dāvā laikus mierīgus,<br>līdz atspīd gaisma mūžīgā.</p><p class="psalms1">Nāc savus bērnus atbalsti<br>kad nāves brīdis pienācis,<br>lai tie ar Tavu gādību<br>tad saņem balvu mūžīgo.</p><p class="psalms2">Lai Tēvam, Garam Svētajam<br>un Tavam Dēlam gods tiek dots,<br>kas Tevi izrotājuši<br>ar žēlastības pilnību. Āmen.</p>';

// Sveika, jūras Zvaigzne
var himnaMarijaVesperes = '<p class="psalms1">Sveika, jūras Zvaigzne,<br>svētā Dieva Māte,<br>jaunava uz mūžiem,<br>cēlie Debess vārti.<p class="psalms2">Pieņemot šo “Sveika!”,<br>Gabriēla teikto,<br>Tu mums dāvā mieru,<br>kļūstot jaunā Ieva.<p class="psalms1">Noņem grēka važas,<br>dāvā prātam gaismu,<br>aizdzen visu ļauno,<br>vairo mūsos labo!<p class="psalms2">Esi mūsu Māte,<br>aizstāvi pie Dieva,<br>mūsu Pestītāja,<br>kurš no Tevis dzima!</p><p class="psalms1">Jaunava vislaipnā,<br>šķīstī mūsu sirdis,<br>lai, no grēkiem brīvi,<br>skaidrāki mēs kļūtu!</p><p class="psalms2">Svētai dzīvei māci,<br>drošu ceļu rādi,<br>lai mēs, redzot Jēzu,<br>līksmotos bez gala!<p class="psalms1">Slava Dievam Tēvam,<br>Dēlam, Svētam Garam –<br>Trīsvienīgam Dievam<br>visos mūžu mūžos! Āmen.</p>';

var himnaMarijaSveikaJurasZvaigzneClassic = '<p class="psalms1">Sveika, jūras Zvaigzne,<br>spožā Dieva Māte;<br>vienmēr tīra, svēta<br>mirdzi debess mājās!</p><p class="psalms2">Pieņemot sveicienu<br>Tu no Gabriēla,<br>vadi Ievas bērnus<br>pestīšanas ceļā!</p><p class="psalms1">Noņem grēku važas,<br>sirdīs gaismu iededz,<br>svētī visus ļaudis,<br>viņu vainas dziedē!</p><p class="psalms2">Esi mūsu Māte,<br>aizstāvi pie Dieva,<br>mūsu Pestītāja,<br>kurš no Tevis dzima!</p><p class="psalms1">Jaunava vislaipnā,<br>šķīstī mūsu sirdis,<br>lai, no grēkiem brīvi,<br>skaidrāki mēs kļūtu!</p><p class="psalms2">Svētai dzīvei māci,<br>drošu ceļu rādi,<br>lai mēs Jēzu redzam,<br>mūžam aplaimoti!</p><p class="psalms1">Slava Dievam Tēvam,<br>Dēlam, Svētam Garam –<br>Trīsvienīgam Dievam<br>visos mūžu mūžos! Āmen.</p>';

// Rožukroņa Karaliene laudes un vesperes 7.okt.
var himnaMarijaRozukronis = '<p class="psalms1">Gan liela prieka pārņemtu,<br>gan arī sāpju nomāktu,<br>nu lielā godā ietērptu<br>mēs Tevi, Māte, slavējam.</p><p class="psalms2">Ak, sveicināta, svētā Māt,<br>prieks garīgs Tevi pildīja<br>gan tad, kad Dēlu ieņēmi,<br>gan tad, kad par To rūpējies.</p><p class="psalms1">Ak, sveicināta mocekle,<br>Tu savā sirdī līdzcieti<br>ar Dēlu ērkšķus, ciešanas<br>un krusta nāves mocības.</p><p class="psalms2">Ak, sveicināta Valdniece,<br>Tu mirdzi Debess godībā<br>ar sava Dēla uzvaru<br>un Svētā Gara uguni.</p><p class="psalms1">Jel nāciet, tautas, godināt<br>ar rožu kroņa lūgšanu<br>to Māti, kas mums mācīja,<br>kā Dievu mīlēt patiesi.</p><p class="psalms2">Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>';

}
{// MartyrVirgin
var himnaMartyrVirginLaudes = '<p class="psalms1">Tu māci dzīvot šķīstībā<br>un dāvā spēku mocekļiem,<br>jel uzklausi mūs, Varenais,<br>kas visus svētos atalgo.</p><p class="psalms2">Bij’ drosmīga šī jaunava,<br>tai divi cēli tikumi<br>un divkāršs kronis debesīs, –<br>mēs viņu dziesmām slavējam.</p><p class="psalms1">Par Tevi deva liecību<br>un nebaidījās mocību,<br>tai gara bruņas stipras bij’,<br>Tev savu garu atdeva.</p><p class="psalms2">Bez dusmām brūces paciešot<br>un pasaul’s maldus atraidot,<br>tā māca mūs kā jādzīvo<br>ar nedalītu ticību.</p><p class="psalms1">Un viņai par mums aizbilstot<br>jel atlaid visus parādus,<br>mums grēka tieksmes noslāpē<br>un dāvā savu svētību.</p><p class="psalms2">Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var himnaMartyrVirginVesperes = '<p class="psalms1">Jaunavas Bērns un Mātes izveidotājs,<br>Jaunavas iznēsāts un Viņai dzimis,<br>jaunavas svētkos dziedam mēs tai slavu,<br>pielūdzot Tevi.</p><p class="psalms2">Jaunava Tava divkārt svētlaimīga:<br>uzveica vispirms trauslās miesas dziņas,<br>satrieca pēc tam, mirstot moceklībā,<br>pasaules niekus.</p><p class="psalms1">Nebijās nāves, nedz no nāves rīkiem,<br>izciešot daudzos mocīšanas veidus,<br>asinis lejot, iemantoja laimi<br>debesīs nonākt.</p><p class="psalms2">Aizbilstot viņai, Dievs, Tu mūsu labais,<br>piedod mums grēkus, atbrīvo no soda,<br>lai tīrām sirdīm, dziedam mēs Tev slavu<br>mūžīgi mūžam. Āmen.</p>'; 
var himnaMartyrMoreVesperesSieviesu = '<p class="psalms1">Šo svēto nopelnus un darbus varenos<br>mēs kopā slavēsim ar prieku milzīgu:<br>jo gars mūs mudina tos dziesmām daudzināt,<br>kas cīnās līdz pat uzvarai.</p><p class="psalms2">No viņām vairījās pasaule grimusī,<br>kaut arī palīdzēt sev pati nespēja,<br>to viņi pilnībā pameta sekojot<br>Tev, Kristu, labais karali.</p><p class="psalms1">Gan viņas dusmas, gan ārprātu pacieta, –<br>nedz sāka kurnēt tās, nedz arī žēloties,<br>bet sirdi mierīgu un prātu nosvērtu<br>tie izturēja mocības.</p><p class="psalms2">Kas gan to varētu ar vārdiem izstāstīt,<br>cik daudz Tu dāvanu mocekļiem gatavo!?<br>Ar sārtu uzvaras vainagu rotāti<br>mirdz nu tie spoži debesīs.</p><p class="psalms1">Dievs, Tevi trejādi vienoto lūdzam mēs,<br>no grēkiem mazgā mūs, no ļauna atbrīvo,<br>dod mieru mūžīgo, lai Tevi slavētu<br>caur visiem gadu simteņiem. Āmen.</p>';
}
{// Sv.Sievietes
// (par vienu svēto)
var himnaSievietesLaudes = '<p class="psalms1">Izcilo Kristus kalponi nu teiksim<br>skanīgām balsīm steidzot slavēt to, kas<br>sieviešu spēku, Rakstos cildināto,<br>atdarināja.</p><p class="psalms2">Uz Dievu ticot, cerot un To mīlot<br>dedzīgi, viņa tuvākmīlestībā<br>auga un guva sev ik dienas spēkus<br>palīdzēt citiem.</p><p class="psalms1">Nopelni viņas, lai nu pamudina<br>Tevi, Kungs Jēzu, mazgāt mūs no grēkiem,<br>lai tīrām sirdīm Tevi varam godāt<br>ar slavas dziesmām.</p><p class="psalms2">Debesu Tēvam lai tiek gods un vara,<br>Dēlam lai slava, pielūgsme uz mūžiem,<br>Svētajam Garam līdzvērtīga cieņa<br>tagad un vienmēr. Āmen.</p>';
var himnaSievietesVesperes = '<p class="psalms1">Šo sievieti nu slavēsim,<br>kas varonīga ticībā<br>un kuras svētums daudzināts<br>tiek visā plašā pasaulē.</p><p class="psalms2">Ar svēto mīlu aizdegta,<br>no pasaulīgā vairījās,<br>lai debess mājas sasniegtu,<br>kur bagātība patiesā.</p><p class="psalms1">Ar gavēni tā valdīja<br>pār savu miesu, mielojot<br>ar karstām lūgsnām dvēseli –<br>tā debess priekus mantojot.</p><p class="psalms2">Ak, Kristu, Ķēniņ varenais,<br>kas dāvā drosmi stiprajiem,<br>mēs lūdzam, viņai aizbilstot,<br>jel mūsu lūgsnas uzklausi.</p><p class="psalms1">Tev, Jēzu, vienmēr gods lai skan,<br>kas svētajai šai aizbilstot,<br>mums dāvā svētu cerību<br>un mantojumu mūžīgu. Āmen.</p>';

// (par mūķeni)
}
{//Gani - priesteri
var himnaGaniLaudes = '<p class="psalms1">Kungs Jēzu Kristu, atgriezies pie Tēva,<br>pie labās rokas valdi pāri zemei;<br>mācekļus savus neatstāj Tu vienus<br>pasaulē šajā.</p><p class="psalms2">Aizstāvi sūti – Patiesības Garu.<br>Atziņu dod Viņš, cerību un gaismu.<br>Baznīcu vada cauri laikiem droši,<br>pilnībā ieved.</p><p class="psalms1">Praviešus dāvā – tautas vadītājus,<br>gudrības pilni pavada tie ceļā.<br>Ganus Viņš ieceļ un caur viņu vārdiem<br>tuvu mums paliek.</p><p class="psalms2">Liecību dod tie, bezbailīgi runā,<br>stiprina vājos, sapulcina tālos,<br>māca ar spēku, palīdz saviem brāļiem<br>sludināt Tevi.</p><p class="psalms1">Slava lai Tēvam augstā goda tronī,<br>slava lai Dēlam, kuru atsūtīja,<br>slava lai Garam, kurš no abiem iziet,<br>vienmēr un mūžam. Āmen.</p>';

var GaniLaudes1part = '<p class="psalms1">Izcilā gana, gudrā garīgtēva<br>uzvaru dižo godinām, jo tagad<br>ticības nesējs priecājas bez gala<br>debesu galmā.</p><p class="psalms2">' ;
var PavestsLaudes = 'Pētera krēslā sēdināts viņš tika,<br>mācīt un vadīt lielo ganāmpulku,<br>debesu valsti izplatīt virs zemes<br>ar Kunga spēku.';
var BiskapsLaudes = 'Pienākums svēts tam bija Kunga dāvāts –<br>svētdarīt, vadīt, mācīt Dieva tautu,<br>gudrībā svētā viņš tai gatavoja<br>debesu veltes.';
var PriesterisLaudes = 'Izcili veicās viņam vadīt tautu –<br>paraugu pats ar svētu dzīvi sniedza<br>un vienmēr centās, sirdi neviltotu,<br>pakalpot Dievam.';
var GaniLaudes2part = '</p><p class="psalms1">Tagad nu lūgsim viņu, cik vien spēka,<br>lai palīdz atbrīvoties mums no grēka<br>un savām lūgsnām stiprina mūs ceļā<br>uz debess mājām.</p><p class="psalms2">Lai Dievam vienam gods un atzinība,<br>debesīs slava, cieņa nemitīga,<br>likumiem saviem gudrajiem Viņš valda<br>pasauli visu. Āmen.</p>';
//***
var himnaGaniPavestsLaudes = GaniLaudes1part + PavestsLaudes + GaniLaudes2part;
var himnaGaniBiskapsLaudes = GaniLaudes1part + BiskapsLaudes + GaniLaudes2part;
var himnaGaniPriestrisLaudes = GaniLaudes1part + PriesterisLaudes + GaniLaudes2part;

var GaniVesperes1part = '<p class="psalms1">Tev himnu dziedam, svētais vīr,<br>tu tikumības paraugs spilgts,<br>jo tas, kas tevi cildina,<br>dod godu Dievam debesīs.</p><p class="psalms2">Kungs Kristus, Augstais Priesteris,<br>no nāves ļaudis izglāba,<br>ar Dievu samierināja<br>un deva Jauno Derību.</p><p class="psalms1">Pats tevi izvēlējās Viņš<br>par žēlastības kalpu mums,<br>kas ļaudīm dotu dzīvību<br>un Tēvu pagodinātu.</p><p class="psalms2">' ;
var PavestsVesperes = 'Kad saņēmi tu Atslēgas,<br>ko mantoji no Pētera,<br>par ganāmpulku rūpējies<br>ar vārdiem, darbiem, piemēru.';
var BiskapsVesperes = 'Kad priesterības pilnību<br>no Svētā Gara saņēmi,<br>kā bīskaps tautu mieloji<br>ar Dieva maizi sātīgo.';
var PriesterisVesperes = 'Tev uzticēja Karalis<br>par Viņa tautu rūpēties:<br>to visu dzīvi mācīji<br>kā priesteris un upuris.';
var GaniVesperes2part ='</p><p class="psalms1">Nu lielā godā debesīs<br>par svēto aizlūdz Baznīcu,<br>lai visi Viņas locekļi<br>tik Kristū laimi meklētu!</p><p class="psalms2">Lai Trīsvienībai gods tiek dots,<br>kas tevi, kalpu centīgo,<br>ar pienācīgām dāvanām<br>nu iepriecina debesīs. Āmen.</p>';
//***
var himnaGaniPavestsVesperes = GaniVesperes1part + PavestsVesperes + GaniVesperes2part;
var himnaGaniBiskapsVesperes = GaniVesperes1part + BiskapsVesperes + GaniVesperes2part;
var himnaGaniPriestrisVesperes = GaniVesperes1part + PriesterisVesperes + GaniVesperes2part;


var himnaGaniMultiLaudes = '<p class="psalms1">Priesteri svētie, Kunga izvēlētie,<br>upuri svēto dāvāt Viņa ļaudīm<br>un tautu vadīt pestīšanas ceļā<br>ar mīlestību.</p><p class="psalms2">Sargājot Dieva dotās žēlastības,<br>apjoztiem gurniem – tā kā Kristus teica,<br>tie apņēmīgi nesa Viņa tautai<br>ticības gaismu.</p><p class="psalms1">Gatavi bija tūlīt atvērt durvis,<br>Pestītājs, atnācis, kad pie tām klauvēs.<br>iet Kungam pretī un ar mīlestību<br>sagaidīt Viņu.</p><p class="psalms2">Augstāko godu, cieņu, slavu dodam,<br>Tev, kungu Kungam, Dievam mūžīgajam,<br>mēs un it viss, ko radījis Tu esi,<br>tagad un mūžam. Āmen.</p>';

var himnaGaniMultiVesperes = '<p class="psalms1">Ar prieku šodien slavējam,<br>kā katru gadu pieminot,<br>mēs svētos ganus godinām,<br>kas Dieva tautu vadīja.</p><p class="psalms2">Par ganāmpulku gādājot,<br>bez atelpas tie strādāja,<br>to sargāja un deva tam<br>ēst labākos no ēdieniem.</p><p class="psalms1">No vilkiem sargā aplokus<br>un laupītājus padzen prom,<br>tie avis labi pabaro<br>un kūti nekad neatstāj.</p><p class="psalms2">Nu svētie gani mūžībā,<br>jūs svētlaimību saņēmāt,<br>mums žēlastību izlūdziet<br>no debess Soģa taisnīgā.</p><p class="psalms1">Ak, Kristu, augstais priesteri,<br>Tev vienmēr mūžīgs gods lai skan,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>';
}
{// doktori/mācītāji
var himnaDoctorLaudes = '<p class="psalms1">Mācītājs, Kristu, mūžīgs Tu un gādīgs,<br>kas ļaudīm atklāj pestīšanas ceļu.<br>Tev vienam pieder vārdi, kas mums dāvā<br>mūžīgo dzīvi.</p><p class="psalms2">Lūdzam mēs Tevi, vispasaules Valdniek,<br>atbalsti stipriem vārdiem allaž savu<br>Līgavu, lai tā nepārstātu būt par<br>pasaules gaismu.</p><p class="psalms1">Tu pie mums sūti savus krietnos kalpus,<br>svētumā viņi mirdz kā debess zvaigznes,<br>mācību Tavu ļaudīm lai tie vienmēr<br>atgādinātu.</p><p class="psalms2">Mācītāj, lai nu skan Tev slavas dziesmas –<br>ar Gara veltēm brīnišķām Tu pildi<br>praviešus, lai tie droši visiem teiktu<br>dzīvības vārdus.</p><p class="psalms1">Lai svētais, ko mēs tagad pagodinām,<br>aizbilstot palīdz Tavai tautai staigāt<br>pa gaismas ceļiem līdz tā Tevi slavēs<br>debesu gaismā. Āmen.</p>';

var himnaDoctorMultiVesperes = himnaGaniMultiVesperes;

himnaDoctorVesperes = '</p><p class="psalms1">Ar gaismu, Saule mūžīgā,<br>Tu pildi visu radīto,<br>visaugstā gaisma dvēselēm,<br>Tev mūsu sirdis slavu dzied.</p><p class="psalms2">Ar savu Garu gādīgo<br>Tu aizdedz dzīvos gaismekļus,<br>kas cauri visiem gadsimtiem<br>mūs pestīšanas ceļā ved.</p><p class="psalms1">Tos vārdus, ko no debesīm<br>prāts dabiskais ir saņēmis,<br>šie žēlastības kalpi mums<br>ļauj jaunā gaismā ieraudzīt.</p><p class="psalms2">Par savu darbu atalgots,<br>kas dāvā gaismu ticīgiem,<br>nu svēto pulkā debesīs<br>mirdz vīrs, ko šodien godinām.</p><p class="psalms1">Mēs lūdzam, viņam aizbilstot,<br>Dievs ceļu atrast palīdzi,<br>kas patiesībā vadīs mūs<br>līdz Tavas mājas sasniegsim.</p><p class="psalms2">To dāvā mums, vismīļais Tēvs,<br>un Dēls, kas Tēvam līdzvērtīgs,<br>ar Svēto Garu, Aizstāvi,<br>kas kopā valdāt mūžīgi. Āmen.</p>';
}

{// 21.01. Sv. Agnese
var himnaAgnese = '<p class="psalms1">Šai dienā svētā Agnese<br>pie Tēva mājās, atgriezās,<br>Tam savu garu atdeva,<br>kas šķīstīts bija asinīs.</p><p class="psalms2">Par jaunu tā priekš laulībām,<br>bet moceklībai gatava, –<br>uz to, kā kāzu svinībām,<br>tā iet ar seju mirdzošu.</p><p class="psalms1">Kad viņai uguns upuri<br>liek ziedot elku dievekļiem,<br>tā atbild: “Tā gan nedarīs<br>nemūžam Kristus jaunavas!</p><p class="psalms2">Šī uguns nokauj ticību,<br>šī liesma gaismu nonāvē,<br>es gribu asins straumes liet,<br>lai apturētu maldus šos.”</p><p class="psalms1">Lūk, bende paceļ zobenu,<br>uz ceļiem nokrīt jaunava,<br>Dievs sargā viņas tikumu,<br>jo godu pelnījusi tā.</p><p class="psalms2">Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>';
}
{// 26.07. Sv. Joahims un Anna, V.J.Marijas vecāki
var himnaJoahimsAnnaLaudes = '<p class="psalms1">Nakts beidzas, klāt jau auseklis,<br>tam rīta ausma līdzi nāk<br>un saules lēktu pavēsta,<br>kas zemi spožā gaismā tērpj.</p><p class="psalms2">Ir Kristus Saule patiesā,<br>un Viņa Māte – rītausma,<br>kas žēlastību atnes mums<br>ar Annas svēto gādību.</p><p class="psalms1">Ak Anna, sakne auglīgā,<br>Tu koks, kas dāvā dzīvību,<br>mums devi zaru ziedošo,<br>kas zemei Kristu atnesa.</p><p class="psalms2">Ak, Kristus Mātes vecāki,<br>jūs svētais paraugs ģimenēm,<br>caur savas Meitas nopelniem<br>mums piedošanu izlūdziet.</p><p class="psalms1">Tev, Jēzu, vienmēr gods lai skan,<br>no Jaunavas Tu piedzimis,<br>un Tēvam, Garam Svētajam<br>uz visiem laikiem mūžīgi. Āmen.</p>';

var himnaJoahimsAnnaVesperes = himnaJoahimsAnnaLaudes;
}
{// 31.07. Sv.Ignācijs no Lojolas
var himnaIgnacijsNoLojolas = '<p class="psalms1">Lai Ignāciju slavējam<br>kā karapulka vadoni,<br>kas veda cīņā kareivjus,<br>tos vārdiem, darbiem aizraujot.</p><p class="psalms2">To uzvarēt vien iespēja<br>ar mīlestību Debess Kungs –<br>lūk tāpēc viņš tā pūlējās,<br>lai Dieva godu vairotu.</p><p class="psalms1">Ar brāļiem kopā zvērēja:<br>kā kareivji tie cīnīsies,<br>lai Kristus Likums valdītu<br>un maldu ēnas izklīstu.</p><p class="psalms2">Bet Svētā Gara iedvesmots<br>un laiku zīmes vētījot,<br>viņš drošu ceļu atklāja,<br>kas ved uz pestīšanu mūs.</p><p class="psalms1">Viņš izsūtīja mācekļus<br>uz tālām zemēm pasaulē,<br>jo ilgojās lai Baznīcā<br>tiek visas tautas uzņemtas.</p><p class="psalms2">Lai Trīsvienību godinām,<br>kas deva mums šo kareivi<br>kā paraugu lai cīnītos<br>par Kristus godu mūžīgi. Āmen.</p>';
}
{// 08.08. Sv.Dominiks
var himnaDominiks = '<p class="psalms1">Lai cildināts tiek Dominiks,<br>šis svētais Kunga kareivis,<br>tā vārds ir “Kunga īpašums” –<br>viņš Dievam dzīvi veltīja.</p><p class="psalms2">Viņš jaunavības liliju<br>no grēka traipa sargāja,<br>kā lāpa bija aizdedzies,<br>lai glābtu tos, kas postā iet.</p><p class="psalms1">Viņš kājam visur ceļoja,<br>lai stātos pretī naidniekiem<br>bez pasaulīgiem ieročiem,<br>vien Kristū spēku smeļoties.</p><p class="psalms2">Ar vārdiem un ar brīnumiem<br>bez apstājas viņš cīnījās<br>un brāļus visur sūtīja,<br>tos atbalstot ar lūgšanām.</p><p class="psalms1">Lai Trīsvienībai vienotai<br>tiek slava, pateicība, gods,<br>kas, Dominikam aizbilstot,<br>mūs ved uz debess līksmību. Āmen.</p>';  
}
{// 24.08. Sv.Baltolomejs, apustulis
var himnaBartolomejs = '<p class="psalms1">Jau Dieva galma godībā<br>tu mirdzi, svētais Bērtuli,<br>mēs tevi dziesmā slavējam,<br>pie Dieva aizbilsti par mums.</p><p class="psalms2">Kungs vērsa savu skatienu<br>uz tevi acīm mīlošām,<br>jo zināja, ka tava sirds<br>ir patiesa un godīga.</p><p class="psalms1">Ko sludināja pravieši,<br>un ļaudis sen jau gaidīja,<br>stāv tavā priekšā Mesija –<br>prieks milzīgs tevi piepilda.</p><p class="psalms2">Pie sevis saista tevi Viņš<br>ar tādu svētu derību,<br>kas prasa krusta upuri<br>un dāvā vietu Debesīs.</p><p class="psalms1">Tu Kristum, pasaul’s Valdniekam,<br>gan draugs, gan sūtnis pasaulē,<br>Tu Viņam dzīvi dāvāji,<br>lai ļaudis kļūtu laimīgi.</p><p class="psalms2">Lai Kristum visa slava, gods,<br>kas pieņem tavus nopelnus,<br>lai varētu mums debesīs<br>ļaut baudīt prieku mūžīgi. Āmen.</p>';  
}
{// 28.08. Sv.Augustīns
var himnaAugustins = '<p class="psalms1">Priesteris slavens atmirdz debess galmā,<br>mirdzoša zvaigzne mācītāju pulkā,<br>pasaulē visā izplatīja tīro<br>ticības gaismu.</p><p class="psalms2">Debesu Sion, slavē Pestītāju,<br>pilsoni deva tev Viņš izcilnieku,<br>brīnišķā veidā, piepildot ar gaismu,<br>pievērzdams Sev to.</p><p class="psalms1">Ticību svēto sargāja viņš modri,<br>to nostiprinot, apkarojot maldus,<br>grēcīgās tieksmes patiesības straumē<br>mazgājot tīras.</p><p class="psalms2">Ganītāj labais visai Kristus tautai,<br>paraugs tu esi priesteriem un mūkiem,<br>ar savām lūgsnām dari Dieva Vaigu<br>mums labvēlīgu.</p><p class="psalms1">Slava un gods lai Svētai Trīsvienībai,<br>ko zemes dzīvē studēji ar degsmi,<br>eksāmens nolikts, nu To debess galmā<br>apbrīno tieši. Āmen.</p>';  
}
{//29.08. Jāņa Kristītāja nāve
var himnaVesperesKristitajaNave = '<p class="psalms1">Ak, Pestītāja priekšteci<br>un patiesības vēstnesi,<br>Tu, Kristus gaismas lāpnesis,<br>kas ved pie Gaismas mūžīgās.</p><p class="psalms2">Ko pravietiski vēstīji<br>ar vārdiem, darbiem, rīcību,<br>to tiešām apliecināji<br>ar savu nāvi svētīgo.</p><p class="psalms1">Pirms piedzimšanas priecājies<br>par To, kas atnāk pasaulē,<br>bet vēlāk Kristu atklāji,<br>no Viņa lūgdams kristību.</p><p class="psalms2">Ak, Kristītāj, tu liecini<br>ar moceklības asinīm<br>par Dieva Jēra upuri,<br>kas atjaunoja pasauli.</p><p class="psalms1">Vislabais Tēvs, jel dāvā to,<br>ka Jāņa pēdās sekojot,<br>mēs pārpilnībā saņemtu<br>tās dāvanas, ko Kristus dod. Āmen.</p>';  
}
{//03.09. Sv. Gregors lielais
var himnaGregorsLielais = '<p class="psalms1">Kas angļiem Gaismu sūtīja,<br>jau kopā mīt ar eņģeļiem.<br>Kā toreiz, Gregor, pagāniem,<br>tā palīdzi nu ticīgiem.</p><p class="psalms2">Tu varu, mantu atstāji<br>un pasaulīgo godību,<br>lai nabags Jēzum sekotu,<br>kas nabadzības Karalis.</p><p class="psalms1">Tad Kristus, Augstais Priesteris,<br>tev lika vadīt Baznīcu,<br>un Pēteris, kā priekštecis,<br>nu kļuva tev par paraugu.</p><p class="psalms2">Tu Svēto Rakstu dziļumus<br>tik brīnišķīgi skaidroji,<br>jo Debess lietu būtību<br>tev Patiesība mācīja.</p><p class="psalms1">Ak, lielais pāvest, izcilais,<br>tu rota, gaisma Baznīcai,<br>ar savu svēto mācību<br>no briesmām sargā ticīgos.</p><p class="psalms2">Lai slava Tēvam Mūžīgam,<br>gods Dēlam Viendzimušajam<br>un Garam, kas no Abiem nāk,<br>lai  līdzvērtīga pielūgsme. Āmen.</p>';  
}
{//11.11. Sv. Māriņš no Tūras
var himnaMarinsTurasLaudes = '<p class="psalms1">Mūs, Mārtiņ, lūdzu, atbalsti,<br>kas tevi šodien godinām,<br>Tu apustuļiem līdzinies<br>ar dzīvi, nāvi savējo.</p><p class="psalms2">Nu dari to, ko sendienās –<br>dzen projām velna viltības<br>un ved pie prāta bīskapus,<br>lai stiprāka kļūst Baznīca.</p><p class="psalms1">Tu trīsreiz elli uzšķērdi –<br>nu izglāb grēkā slīkstošos;<br>reiz kailam drēbes iedevi –<br>nāc, taisnīgumā ietērp mūs.</p><p class="psalms2">To dedzību, ko sendienās<br>Dievs sirdī tev bij’ ielicis,<br>liec lietā un nāc palīgā<br>gan pāvestam, gan bīskapiem.</p><p class="psalms1">Lai Trīsvienībai gods tiek dots,<br>kam Mārtiņš svēti ticēja,<br>lai viņam lūgsnām aizbilstot<br>Tā mūsu dzīvē darbojas. Āmen.</p>'; 
var himnaMarinsTurasVesperes =  '<p class="psalms1">Svētīgais Kunga sludinātājs, kuru<br>ticīgie visur godina ar prieku,<br>debesīs uzņemts dienā šai, lai gūtu<br>pelnīto balvu.</p><p class="psalms2">Dievbijīgs, prātīgs, pazemīgs un vienkāršs,<br>apdomīgs, šķīsts un mierīgs visu dzīvi –<br>tikumi svētie uzturēja viņam<br>ķermeni možu.</p><p class="psalms1">Uz viņa kapu svētceļoja tauta,<br>slimie tur bieži tika dziedināti,<br>vienalga kādas kaites nomocīti –<br>veseli kļuva.</p><p class="psalms2">Tādēļ mēs visi vienoti ar prieku<br>slavējam viņu, dziedot goda himnu,<br>lai viņa palīdzību varam saņemt<br>it visos laikos.</p><p class="psalms1">Lai dodam slavu, godu mēs un varu<br>Valdniekam mūsu, kas sēž debess tronī –<br>pasaules visas kārtību Viņš valda<br>Viens Trīsvienībā. Āmen.</p>'; 
}
{//15.10. Sv. Terēze no Avilas
var himnaTerezeAvilasLaudes = '<p class="psalms1">Par debess Kungu liecināt<br>no tēva mājām aizbēgi<br>uz mauru zemi, Terēze,<br>par Kristu izliet asinis.</p><p class="psalms2">Bet maigāku un saldāku<br>tev nāvi izvēlējās Kungs –<br>ar Viņa bultu caururbta<br>tu mīlestībā sadegi.</p><p class="psalms1">Ak, žēlsirdības upuri,<br>jel aizdedz mūsu dvēseles<br>un ļaudis, kas tev uzticas,<br>no elles liesmām pasargā.</p><p class="psalms2">Lai Līgavaini dievišķo<br>nu pielūdz svētās jaunavas<br>un kāzu dziesmām slavē To<br>uz visiem laikiem mūžīgi. Āmen.</p>';
var himnaTerezeAvilasVesperes = '<p class="psalms1">Jau diena klāt, kad debesīs<br>kā balta dūja pacēlās<br>uz Dieva svēto mājokli<br>reiz dvēs’le svētai Terēzei.</p><p class="psalms2">Tā Līgavaiņa balsi dzird:<br>“Nāc, māsa, šurp no Karmela<br>uz Dieva Jēra laulībām,<br>lai goda kroni saņemtu.”</p><p class="psalms1">Lai Līgavaini dievišķo<br>nu pielūdz svētās jaunavas<br>un kāzu dziesmām slavē To<br>uz visiem laikiem mūžīgi. Āmen.</p>';
}
{//07.12. Sv. Ambrozijs
var himnaAmbrozijs = '<p class="psalms1">Nu bīskapu mēs godāsim,<br>kas bija svēts un drošsirdīgs,<br>un cauri vētrām briesmīgām<br>reiz Baznīcu viņš izveda.</p><p class="psalms2">No varas draudiem nebijās<br>un Dieva namus sargāja,<br>lai ķeizariskā ģimene<br>tos ariāņiem neatdod.</p><p class="psalms1">Viņš Svēto Rakstu dziļumus<br>mums brīnišķīgi atklāja,<br>un izskaidroja pamatus,<br>uz kuriem balstās ticība.</p><p class="psalms2">Ar sirdi Gara aizdegtu<br>viņš skaistas himnas rakstīja.<br>Par varonību ticībā<br>kā mocekli to godāja.</p><p class="psalms1">Ar savu skaidro mācību,<br>kas visus maldus izkliedē,<br>triec projām ļauno plēsēju,<br>mūs stiprini un aizsargā.</p><p class="psalms2">Lai Trīsvienībai gods tiek dots,<br>ko, tavu lūgsnu balstīti,<br>ar himnām debess pagalmos<br>mēs ceram slavēt mūžīgi. Āmen.</p>';
}
{//26.12. Sv. Stefans
var himnaStefansLaudes = '<p class="psalms1">Kristus ir dzīvība, pasaulē kas ienāk,<br>sadziedē brūces, atbrīvo no nāves,<br>atkal nu sēž pie Tēva labās rokas,<br>valda uz mūžiem.</p><p class="psalms2">Stefans kā pirmais gāja Viņa pēdās,<br>kalpoja Kungam Svētā Gara spēkā,<br>kas, Kunga sūtīts, viņu iedvesmoja<br>cildeniem darbiem.</p><p class="psalms1">Akmeņu krusas nežēlīgi šaustīts,<br>pieņēma trakā pūļa lemto nāvi,<br>naidniekiem lūdza Dieva piedošanu<br>žēlīgu sirdi.</p><p class="psalms2">Raudot mēs lūdzam, mocekli vispirmais,<br>svētītais taisno draudzes piederīgais,<br>no debess mājām ticīgajiem ļaudīm<br>atbalstu sūti.</p><p class="psalms1">Kopā ar mocekļiem mēs līksmi dziedam,<br>godu un slavu Svētai Trīsvienībai,<br>Stefanam pirmam dāvāja Tā kroni<br>pēc smagās cīņas. Āmen.</p>';
}