var template = {
  1: {/*1 = nedēļa*/
  3: {
    1: {
      "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    2: {
            "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    3: {
            "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    4: {
            "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    5: {
            "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    6: {
            "laudes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "ant1": "",
        "ant2": "",
        "ant3": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    }
  },
  }
}

var advents_gavenis_lieldienas = {
  0: {
    "ievadpsalma": "antifonas",
    "1ant": "Lūk, Kungs un ķēniņš nāk - nāciet, viņu pielūgsim!",
    "2ant": "Kritīsim ceļos mūsu Kunga un ķēniņa priekšā – viņš nāk, lai mūs atpestītu.",
    "3ant": "Kungs ir klāt. Nāciet, viņu pielūgsim!"
  },
  1: { /*seko nedēļas dienas*/
    0: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    1: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    2: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    3: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    4: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    5: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    },
    6: {
      "laudes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      },
      "vesperes": {
        "title": "",
        "1ant": "",
        "2ant": "",
        "3ant": "",
        "lasijumstitle": "",
        "lasijumstext": "",
        "atbilde": "responsorijs",
        "1atb": "",
        "2atb": "",
        "3atb": "",
        "4atb": "",
        "5atb": "",
        "6atb": "",
        "magbenant": "",
        "lugumi": "",
        "resplugums": "",
        "1lugums": "",
        "2lugums": "",
        "3lugums": "",
        "4lugums": "",
        "5lugums": "",
        "lugsimies": ""
      }
    }
  },
  2: {
    
  },
  3: {
    
  },
  4: {
    
  },
  5: { /*gavēnim*/
    
  },
  
    25: {
    "laudes": {
      "title": "LAUDES (25.decembris)",
      "ant1": "",
      "ant2": "",
      "ant3": "",
      //psalmi I nedēļas svētdienas Laudēm Psalms 63, Dan 3, Psalms 149
      "lasijumstitle": "LASĪJUMS ",
      "lasijumstext": "",
      "atbilde": "responsorijs",
      "atb1": "",
      "atb2": "",
      "atb3": "",
      "magbenant": "",
      "lugumi": "",
      "resplugums": "- ",
      "lugums1": "",
      "lugums2": "",
      "lugums3": "",
      "lugums4": "",
      "lugsimies": " Caur Jēzu Kristu, mūsu Kungu, kas ar Tevi Svētā Gara vienībā dzīvo un valda, Dievs visos mūžu mūžos."
    },
    "vesperes": {
      "title": "VESPERES (25.decembris)",
      "ant1": "",
      "ant2": "",
      "ant3": "",
            // Psalms 110 (109),1-5.7, Psalms 130 (129), sal. Kol 1,12-20 => psalmi.js
      "lasijumstitle": "LASĪJUMS ",
      "lasijumstext": "",
      "atbilde": "responsorijs",
      "atb1": "",
      "atb2": "",
      "atb3": "",
      "magbenant": "",
      "lugumi": "",
      "resplugums": "- ",
      "lugums1": "",
      "lugums2": "",
      "lugums3": "",
      "lugums4": "",
      "lugums5": "",
      "lugsimies": " Caur Jēzu Kristu, mūsu Kungu, kas ar Tevi Svētā Gara vienībā dzīvo un valda, Dievs visos mūžu mūžos."
    }
    }
}